[139] Product page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #136
Opened 2020-11-26 15:35 UTC by wuhmi

![HTML1](https://user-images.githubusercontent.com/62771719/100368490-f0ec8680-3003-11eb-84dd-29b80105dda5.jpg)
![HTML 2](https://user-images.githubusercontent.com/62771719/100368596-0eb9eb80-3004-11eb-91c1-f2523fa3119e.jpg)
![HTML 3](https://user-images.githubusercontent.com/62771719/100368720-38731280-3004-11eb-9285-20e73e0f5498.jpg)
![HTML 4](https://user-images.githubusercontent.com/62771719/100368879-6b1d0b00-3004-11eb-8752-0a75df6b61e6.jpg)
![HTML 5](https://user-images.githubusercontent.com/62771719/100368938-7f610800-3004-11eb-8a0d-0cf56a68001e.jpg)
![HTML 6](https://user-images.githubusercontent.com/62771719/100369041-ad464c80-3004-11eb-9752-5c6582491fb3.jpg)
![HTML 7](https://user-images.githubusercontent.com/62771719/100369134-cfd86580-3004-11eb-8bd5-7078262789d6.jpg)
![HTML 8](https://user-images.githubusercontent.com/62771719/100369190-e088db80-3004-11eb-8645-5fa1ad099f14.jpg)
![HTML 9](https://user-images.githubusercontent.com/62771719/100369299-07471200-3005-11eb-9b07-bbf0bcb3f1e5.jpg)
![HTML 10](https://user-images.githubusercontent.com/62771719/100369409-23e34a00-3005-11eb-9173-04d0d5583801.jpg)
![HTML 11](https://user-images.githubusercontent.com/62771719/100369511-3eb5be80-3005-11eb-9dd3-c765221a1851.jpg)

2020-11-26 15:43 UTC, adaugochi requested changes
Well done @wuhmi 

You are expected to use just 2 images for this task. Kindly remove all other images that are not in use

2020-11-27 10:04 UTC, Ireti203 requested changes

2020-11-27 10:04 UTC, Ireti203 commented on submissions/omawumiRebeccaMoju/HTML/BLK.html
> +<header>
You already used the header tag above. You can use main here instead of using the header tag again.

2020-11-27 10:04 UTC, Ireti203 commented on submissions/omawumiRebeccaMoju/HTML/BLK.html
> +</header>
Kindly format properly.

2020-11-27 10:56 UTC, Ireti203 requested changes

2020-11-27 10:56 UTC, Ireti203 commented on submissions/omawumiRebeccaMoju/HTML/BLK.html
>      <p> &copy; 2020 Online BLK_My Naturals</p>
Are you sure you want to display your products list in the footer? It's best you still put it within the main tag. @wuhmi

2020-11-27 11:33 UTC, Ireti203 requested changes
Kindly change this file name to a more descriptive title. BLK.html is not descriptive

2020-11-27 11:41 UTC, Ireti203 requested changes
Kindly remove the BLK and leave it as productpage.html. Also, note that there should be no spacing in file naming.

2020-11-27 11:47 UTC, Ireti203 commented on submissions/omawumiRebeccaMoju/HTML/BLK productpage.html
> +</nav>
Kindly format properly

2020-11-27 11:47 UTC, Ireti203 commented on submissions/omawumiRebeccaMoju/HTML/BLK productpage.html
> +    </section>
Format properly

2020-11-27 12:45 UTC, Ireti203 approved these changes

2020-11-27 12:45 UTC, merged