[137] Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #144
Opened 2020-11-27 09:45 UTC by zao12345

![webpage 1](https://user-images.githubusercontent.com/74374137/100434895-7b34f900-309d-11eb-986d-0b088f639039.JPG)
![webpage 2](https://user-images.githubusercontent.com/74374137/100434900-7cfebc80-309d-11eb-8e0c-b69a47783fc9.JPG)

2020-11-27 11:17 UTC, Ireti203 requested changes

2020-11-27 11:17 UTC, Ireti203 commented on submissions/ZainabAbdussalam-Osimade/HTML/Product.html
> +
Your code is not properly formatted. You do not need to leave a line after every  line of code, kindly remove whitespaces. The body tag is not properly formatted.

2020-11-27 11:17 UTC, Ireti203 commented on submissions/ZainabAbdussalam-Osimade/HTML/Product.html
> +            <b>Feature</b>
KIndly format properly

2020-11-27 11:17 UTC, Ireti203 commented on submissions/ZainabAbdussalam-Osimade/HTML/Product.html
> +</body>
Same here

2020-11-28 10:21 UTC, adaugochi requested changes
Remove spaces on image name. Use `camelCase`, `PascalCase`, `snake_case` or `kebab-case` for naming thing

2020-11-28 11:29 UTC, Ireti203 approved these changes

2020-11-28 23:13 UTC, adaugochi approved these changes

2020-11-28 23:13 UTC, merged