[139] Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #153
Opened 2020-11-29 13:56 UTC by olakanmigoodnessb

![Capture 1](https://user-images.githubusercontent.com/74025661/100543917-f4c21800-3252-11eb-96b0-049491c5ae2e.PNG)
![Capture 2](https://user-images.githubusercontent.com/74025661/100543919-f68bdb80-3252-11eb-9e99-4152d380f1a8.PNG)
![Capture 3](https://user-images.githubusercontent.com/74025661/100543924-fa1f6280-3252-11eb-8a2f-146a919e9e42.PNG)
![Capture 4](https://user-images.githubusercontent.com/74025661/100543928-fe4b8000-3252-11eb-8ced-559f0daa25a4.PNG)

2020-11-30 09:07 UTC, Ireti203 requested changes

2020-11-30 09:07 UTC, Ireti203 commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +
Remove whitespace

2020-11-30 09:07 UTC, Ireti203 commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +
Remove whitespace

2020-11-30 09:07 UTC, Ireti203 commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +	</section>
Format properly

2020-11-30 09:07 UTC, Ireti203 commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +	</section>
Format properly

2020-11-30 09:07 UTC, Ireti203 commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +
Remove whitespace

2020-11-30 21:19 UTC, olakanmigoodnessb commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +	</section>
I have removed the div and section.

2020-11-30 21:19 UTC, olakanmigoodnessb commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +
I have removed it.

2020-11-30 21:20 UTC, olakanmigoodnessb commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +
I have removed it.

2020-11-30 21:20 UTC, olakanmigoodnessb commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +	</section>
I have.

2020-11-30 21:20 UTC, olakanmigoodnessb commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +	</section>
I have.

2020-11-30 21:20 UTC, olakanmigoodnessb commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +
I have.

2020-12-01 10:42 UTC, Ireti203 requested changes

2020-12-01 10:42 UTC, Ireti203 commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +<!-- This section is for products-->
You did not close this section

2020-12-01 21:15 UTC, olakanmigoodnessb commented on submissions/goodnessOlakanmi/HTML/Product-page.html
> +<!-- This section is for products-->
I have

2020-12-02 10:12 UTC, Ireti203 approved these changes

2020-12-02 10:12 UTC, merged