[138] Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #163
Opened 2020-11-30 16:29 UTC by Nelyne

2020-11-30 16:31 UTC, Nelyne commented
![Annotation 2020-11-30 160250](https://user-images.githubusercontent.com/54291845/100636341-e5fe6280-3331-11eb-94ba-64190d6c5284.png)
![Annotation 2020-11-30 160510](https://user-images.githubusercontent.com/54291845/100636371-ed257080-3331-11eb-8fe5-345e0d9852b8.png)

2020-12-01 22:22 UTC, Ireti203 requested changes

2020-12-01 22:22 UTC, Ireti203 commented on submissions/nkeirukaEnendu/HTML/index.html
> +
Remove whitespace

2020-12-01 22:22 UTC, Ireti203 commented on submissions/nkeirukaEnendu/HTML/index.html
> +
Remove whitespace

2020-12-01 22:22 UTC, Ireti203 commented on submissions/nkeirukaEnendu/HTML/index.html
> +
Remove whitespace

2020-12-02 10:22 UTC, Ireti203 approved these changes

2020-12-02 10:22 UTC, merged