[134] About me
Dufuna-CodeCamp/Dufuna-Fem pull request #170
Opened 2020-12-01 01:38 UTC by odun-netizen

My aim for Dufuna-Fem Camp

2020-12-01 08:43 UTC, Ireti203 requested changes
You have two .txt files. Kindly remove one.

2020-12-01 14:29 UTC, odun-netizen commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Good afternoon,I have deleted one of the .txt files. Sent from Mail for Windows 10 From: Ireti203Sent: Tuesday, December 1, 2020 9:44 AMTo: Dufuna-CodeCamp/Dufuna-FemCc: odun-netizen; AuthorSubject: Re: [Dufuna-CodeCamp/Dufuna-Fem] [134] About me (#170) @Ireti203 requested changes on this pull request.You have two .txt files. Kindly remove one.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

2020-12-01 21:27 UTC, Ireti203 approved these changes

2020-12-01 21:29 UTC, merged

2020-12-22 00:07 UTC, odun-netizen commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Good morning.I am currently working on a task but in making my pull request I can’t see my folder I created in the submissions folder.I hope to hear favorably from you  Sent from Mail for Windows 10 From: Ireti203Sent: Tuesday, December 1, 2020 9:44 AMTo: Dufuna-CodeCamp/Dufuna-FemCc: odun-netizen; AuthorSubject: Re: [Dufuna-CodeCamp/Dufuna-Fem] [134] About me (#170) @Ireti203 requested changes on this pull request.You have two .txt files. Kindly remove one.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 