[148]  Add Page Navigation to your Pages- Fullstack
Dufuna-CodeCamp/Dufuna-Fem pull request #196
Opened 2020-12-02 14:16 UTC by Mariamidowu

![Screenshot 2020-12-02 080833](https://user-images.githubusercontent.com/74326099/100884049-a3926e00-3476-11eb-847d-80c4d43fb537.jpg)
![Screenshot 2020-12-02 080915](https://user-images.githubusercontent.com/74326099/100884060-a55c3180-3476-11eb-8466-9bb4e5bc39e4.jpg)
![Screenshot 2020-11-30 162639](https://user-images.githubusercontent.com/74326099/100884066-a68d5e80-3476-11eb-98ca-9001a4c5cfd2.jpg)

2020-12-04 10:52 UTC, Ireti203 requested changes
Remove the debug.log in the html-forms folder

2020-12-04 10:54 UTC, Ireti203 reviewed
Why did you include a survey form in this task? The content is similar to the contact-form.

2020-12-04 19:22 UTC, Mariamidowu commented
Gooday ma! I have deleted the survey form and also I was following the
video on the app, that's why it's there

On Fri, Dec 4, 2020, 11:54 AM Ireti203 <notifications@github.com> wrote:

> *@Ireti203* commented on this pull request.
>
> Why did you include a survey form in this task? The content is similar to
> the contact-form.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/196#pullrequestreview-544854387>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARXCAUYKY2GRJOSZXF2OXB3STC5XTANCNFSM4UKRWIIA>
> .
>

2020-12-06 14:02 UTC, Ireti203 commented
Kindly resolve the conflicts on this branch.

2020-12-08 10:01 UTC, Ireti203 commented
Do you have challenges resolving the conflicts on this PR? @Mariamidowu

2020-12-08 10:54 UTC, Mariamidowu commented
Yes ma. I have tried to remove it but it's not working.

On Tue, Dec 8, 2020, 11:01 AM Ireti203 <notifications@github.com> wrote:

> Do you have challenges resolving the conflicts on this PR? @Mariamidowu
> <https://github.com/Mariamidowu>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/196#issuecomment-740518256>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARXCAU6XHNLHSMOQET54NETSTX2PTANCNFSM4UKRWIIA>
> .
>

2020-12-10 08:03 UTC, Mariamidowu commented
Good day ma! I have removed the white space on the contact form and I have also deleted the files

2020-12-12 09:46 UTC, adaugochi requested changes

2020-12-12 09:46 UTC, adaugochi commented on submissions/idowuMariam/html-forms/product-page.html
> +<!DOCTYPE html>
Hello @Mariamidowu 

You don't have to create a product page in your `html-forms` folder. You already have this file in your `HTML` folder. Kindly link the pages on those already existing file. Like I said. You don't have to create a new file

2020-12-12 09:46 UTC, adaugochi commented on submissions/idowuMariam/html-forms/Contact-form.html
> +<!DOCTYPE html>
Before working on `Add page Navigation` task, I believe that you must have work on creating a contact form page before. So, you don't have to create a new contact form page again. Kindly work on adding navigation links to those already existing pages

2020-12-12 09:58 UTC, closed without merging