[143] Develop a Contact Form Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #207
Opened 2020-12-03 15:05 UTC by lorlahdey

![image7](https://user-images.githubusercontent.com/19871450/101046407-50591200-3581-11eb-8d98-eec80e55da0d.PNG)

2020-12-04 09:46 UTC, Ireti203 requested changes

2020-12-04 09:46 UTC, Ireti203 commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +    <!-- Contact Us Form -->
Remove whitespaces

2020-12-04 09:46 UTC, Ireti203 commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +                    <label><strong>Subject:</strong></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Kindly remove the extra characters after the closing tag. The section is also not properly formatted.

2020-12-04 09:46 UTC, Ireti203 commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +    <!-- Footer Begins -->
Remove extra whitespaces

2020-12-04 09:46 UTC, Ireti203 commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +
Remove extra whitespaces

2020-12-04 15:55 UTC, lorlahdey commented
Ireti

2020-12-07 13:36 UTC, Ireti203 approved these changes

2020-12-07 13:37 UTC, merged