[149] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-Fem pull request #211
Opened 2020-12-03 16:10 UTC by lorlahdey

![Capture8](https://user-images.githubusercontent.com/19871450/101055566-50114480-358a-11eb-9d5b-bc52ad56cf11.PNG)
![Capture9](https://user-images.githubusercontent.com/19871450/101055588-53a4cb80-358a-11eb-8daa-2404af874871.PNG)

Kemiojo

2020-12-04 14:35 UTC, Ireti203 requested changes

2020-12-04 14:35 UTC, Ireti203 commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +    <!-- Contact Us Form -->
Remove whitespaces

2020-12-04 14:35 UTC, Ireti203 commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +</section>
Format properly

2020-12-04 14:37 UTC, Ireti203 commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +    <!-- Footer Begins -->
Remove whitespaces

2020-12-04 14:37 UTC, Ireti203 commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +
Remove whitespaces

2020-12-04 15:55 UTC, lorlahdey commented
Ireti

2020-12-07 09:41 UTC, Ireti203 commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +                        <label for="email"><strong>Email:</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
what is the "&nbsp" for? Kindly remove all unnecessary characters.

2020-12-07 15:53 UTC, Ireti203 commented
There are conflicts on this branch. You should resolve this

2020-12-08 10:58 UTC, lorlahdey commented
How can i resolve the conflicts?

2020-12-12 09:54 UTC, adaugochi requested changes

2020-12-12 09:54 UTC, adaugochi commented on submissions/lawalLolade/html-forms/contactFormPage.html
> +<head>
Also, I can see that you already have contactFormPage before, Why are you creating a new one?
![image](https://user-images.githubusercontent.com/43061141/101980807-6729f380-3c68-11eb-9c4c-e1f72fcd4a98.png)

2020-12-14 07:01 UTC, Ireti203 approved these changes

2020-12-14 07:02 UTC, merged