[150] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-Fem pull request #216
Opened 2020-12-04 09:26 UTC by Kafabidemi

![11](https://user-images.githubusercontent.com/74104576/101146302-205e4d00-361b-11eb-9c9a-a15001495fca.PNG)
![12](https://user-images.githubusercontent.com/74104576/101146308-22281080-361b-11eb-802c-7c17f5fac274.PNG)

2020-12-04 10:48 UTC, Ireti203 requested changes
Remove the spacing in your file names

2020-12-04 11:29 UTC, Kafabidemi commented
Done, Kindly Review


On Fri, Dec 4, 2020 at 11:49 AM Ireti203 <notifications@github.com> wrote:

> *@Ireti203* requested changes on this pull request.
>
> Remove the spacing in your file names
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/216#pullrequestreview-544850154>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARVL6AHUKVNZMTSKVK7CAYDSTC5CLANCNFSM4UNFTZDA>
> .
>

2020-12-06 14:51 UTC, Ireti203 reviewed
Kindly rename the Product.html file as product.html

2020-12-06 14:51 UTC, Ireti203 commented on submissions/adeyemoKafayat/html-forms/contactform.html
> +			</form>
Kindly format properly

2020-12-06 14:51 UTC, Ireti203 commented on submissions/adeyemoKafayat/html-forms/contactform.html
> +            <li><a href="#">Cart</a></li>
Format properly

2020-12-06 14:51 UTC, Ireti203 commented on submissions/adeyemoKafayat/HTML/Product.html
> +            <li><a href="#">Cart</a></li>
Format properly

2020-12-07 10:19 UTC, Ireti203 requested changes
This task ought to include only the navigations added to your page. You already have the product.html file in your folder before, you dont have to create another.

2020-12-07 11:58 UTC, Kafabidemi commented
Changes made, Kindly review

On Mon, Dec 7, 2020 at 11:19 AM Ireti203 <notifications@github.com> wrote:

> *@Ireti203* requested changes on this pull request.
>
> This task ought to include only the navigations added to your page. You
> already have the product.html file in your folder before, you dont have to
> create another.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/216#pullrequestreview-546007347>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARVL6AGSIMQJ7NM3NPE3NQDSTST3DANCNFSM4UNFTZDA>
> .
>

2020-12-08 11:55 UTC, Ireti203 approved these changes

2020-12-08 11:56 UTC, merged