[148] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-Fem pull request #217
Opened 2020-12-04 09:31 UTC by Constancia2

![contact form](https://user-images.githubusercontent.com/74066153/101146855-d4f86e80-361b-11eb-98d3-5b6991e4bf84.png)
![product](https://user-images.githubusercontent.com/74066153/101146868-d88bf580-361b-11eb-89f5-3370f8bfda55.png)

2020-12-04 14:18 UTC, Ireti203 reviewed
Remove the settings.json file in your html-forms folder

2020-12-04 14:18 UTC, Ireti203 commented on submissions/OnyediriConstancia/html-forms/ContactForm.html
> +</fieldset>
Format properly

2020-12-04 14:21 UTC, Constancia2 commented
Pls ma I don't understand the settings . Json , you are talking about. I
can't find it inside
On Dec 4, 2020 3:18 PM, "Ireti203" <notifications@github.com> wrote:

> *@Ireti203* commented on this pull request.
>
> Remove the settings.json file in your html-forms folder
> ------------------------------
>
> In submissions/OnyediriConstancia/html-forms/ContactForm.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/217#discussion_r536127619>
> :
>
> > +
> +<legend>Contact Form</legend>
> +<label for="firstname">First Name;</label>
> +<input type="text" name="firstname" id="firstname"> <br><br>
> + <label for="lastname"> Last Name; </label>
> + <input type="text" name="lastname" id="lastname"> <br><br>
> + <label for="email">Email; </label>
> + <input type="email" name="email" id="email" placeholder="Enter your email address"><br><br>
> +
> + <label>Subject;</label>
> + <input list="subject-list" id="subject" name="subject">
> + <datalist id="subject-list">
> +
> +<option value="Product">
> +<option value="ContactForm">
> +<option value="Morehair">
> + </datalist><br><br>
> + <label for="">Write a feedback/Suggestion about our product.</label><br>
> + <textarea name="Comments" id="comments" cols="30" rows="10"></textarea><br><br>
> +
> +<button type="submit">Submit</button>
> +</fieldset>
>
> Format properly
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/217#pullrequestreview-544992550>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARVCR2P3XZDWXTJBDTK6IX3STDVSZANCNFSM4UNF2C6A>
> .
>

2020-12-04 14:22 UTC, Ireti203 commented
In the html-forms folder, you have a .vscode file

2020-12-04 14:24 UTC, Constancia2 commented
Okay
On Dec 4, 2020 3:23 PM, "Ireti203" <notifications@github.com> wrote:

> In the html-forms folder, you have a .vscode file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/217#issuecomment-738810850>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARVCR2ND4IQ5NI5Z4CY2BITSTDWFJANCNFSM4UNF2C6A>
> .
>

2020-12-04 14:36 UTC, Constancia2 commented
The problem here is that I have removed the file but I can't push because
the other PR name is interfering. I don't know how to change it to the
former . I used git checkout is telling me the name already exist
On Dec 4, 2020 3:24 PM, "Pretty Stancia" <prettystancia@gmail.com> wrote:

> Okay
> On Dec 4, 2020 3:23 PM, "Ireti203" <notifications@github.com> wrote:
>
>> In the html-forms folder, you have a .vscode file
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/217#issuecomment-738810850>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ARVCR2ND4IQ5NI5Z4CY2BITSTDWFJANCNFSM4UNF2C6A>
>> .
>>
>

2020-12-06 14:26 UTC, Ireti203 requested changes

2020-12-06 14:26 UTC, Ireti203 commented on submissions/OnyediriConstancia/html-forms/ContactForm.html
> +
Remove whitespace

2020-12-06 14:26 UTC, Ireti203 commented on submissions/OnyediriConstancia/html-forms/ContactForm.html
> +
Remove whitespace

2020-12-06 14:26 UTC, Ireti203 commented on submissions/OnyediriConstancia/html-forms/ContactForm.html
> +
Remove whitespace

2020-12-06 14:26 UTC, Ireti203 commented on submissions/OnyediriConstancia/html-forms/ContactForm.html
> +</fieldset>
Format properly

2020-12-06 14:30 UTC, Constancia2 commented
I don't understand the meaning of the white space .
On Dec 6, 2020 3:27 PM, "Ireti203" <notifications@github.com> wrote:

> *@Ireti203* requested changes on this pull request.
> ------------------------------
>
> In submissions/OnyediriConstancia/html-forms/ContactForm.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/217#discussion_r537049023>
> :
>
> > @@ -0,0 +1,45 @@
> +<!DOCTYPE html>
> +<html lang="en">
> +<head>
> +    <meta charset="UTF-8">
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +    <title>CONTACT FORM</title>
> +</head>
> +<body>
> +
> +    <h1>JUSTHAIR</h1>
> +    <ul>
> +        <a href="product.html"> <li> Product</li></a>
> +        <a href="ContactForm.html">  <li>ContactForm</li></a>
> +        <a href="morehair.html"> <li>MoreHair</li></a>
> +
>
> Remove whitespace
> ------------------------------
>
> In submissions/OnyediriConstancia/html-forms/ContactForm.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/217#discussion_r537049379>
> :
>
> > +<html lang="en">
> +<head>
> +    <meta charset="UTF-8">
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +    <title>CONTACT FORM</title>
> +</head>
> +<body>
> +
> +    <h1>JUSTHAIR</h1>
> +    <ul>
> +        <a href="product.html"> <li> Product</li></a>
> +        <a href="ContactForm.html">  <li>ContactForm</li></a>
> +        <a href="morehair.html"> <li>MoreHair</li></a>
> +
> +    </ul>
> +
>
> Remove whitespace
> ------------------------------
>
> In submissions/OnyediriConstancia/html-forms/ContactForm.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/217#discussion_r537049523>
> :
>
> > +    <meta charset="UTF-8">
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +    <title>CONTACT FORM</title>
> +</head>
> +<body>
> +
> +    <h1>JUSTHAIR</h1>
> +    <ul>
> +        <a href="product.html"> <li> Product</li></a>
> +        <a href="ContactForm.html">  <li>ContactForm</li></a>
> +        <a href="morehair.html"> <li>MoreHair</li></a>
> +
> +    </ul>
> +
> +    <p> <strong>  Welcome to JustHair your number one online store for quality lush hair.</strong> </p>
> +
>
> Remove whitespace
> ------------------------------
>
> In submissions/OnyediriConstancia/html-forms/ContactForm.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/217#discussion_r537049583>
> :
>
> > +    <fieldset>
> +
> +<legend>Contact Form</legend>
> +<label for="firstname">First Name;</label>
> +<input type="text" name="firstname" id="firstname"> <br><br>
> + <label for="lastname"> Last Name; </label>
> + <input type="text" name="lastname" id="lastname"> <br><br>
> + <label for="email">Email; </label>
> + <input type="email" name="email" id="email" placeholder="Enter your email address"><br><br>
> +
> + <label>Subject;</label>
> + <input list="subject-list" id="subject" name="subject">
> + <datalist id="subject-list">
> +
> +<option value="Product">
> +<option value="ContactForm">
> +<option value="Morehair">
> + </datalist><br><br>
> + <label for="">Write a feedback/Suggestion about our product.</label><br>
> + <textarea name="Comments" id="comments" cols="30" rows="10"></textarea><br><br>
> +
> +<button type="submit">Submit</button>
> +</fieldset>
>
> Format properly
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/217#pullrequestreview-545710635>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARVCR2OCJVT4PM3C4SJOUT3STOIDXANCNFSM4UNF2C6A>
> .
>

2020-12-07 13:34 UTC, merged