[157] Style the Contact Us Page using CSS
Dufuna-CodeCamp/Dufuna-Fem pull request #221
Opened 2020-12-04 14:10 UTC by HalimahOladimeji

Laptop view
![Screenshot 2020-12-04 010835](https://user-images.githubusercontent.com/73618133/101171818-9c1ec080-3640-11eb-972e-61cf1bf1cf8c.png)
![Screenshot 2020-12-04 145716](https://user-images.githubusercontent.com/73618133/101172133-0df70a00-3641-11eb-9363-b9672c272ae5.png)
Tablet view
![Screenshot 2020-12-04 150525](https://user-images.githubusercontent.com/73618133/101173051-46e3ae80-3642-11eb-9f8f-bc237aa05583.png)
![Screenshot 2020-12-04 150611](https://user-images.githubusercontent.com/73618133/101173059-49de9f00-3642-11eb-9d09-a41f5073efb2.png)
Mobile view
![Screenshot 2020-12-04 012121](https://user-images.githubusercontent.com/73618133/101173202-7db9c480-3642-11eb-89a8-259ddfc8079c.png)
![Screenshot 2020-12-04 012217](https://user-images.githubusercontent.com/73618133/101173225-827e7880-3642-11eb-9fa5-3730f2964e55.png)

2020-12-04 14:25 UTC, Ireti203 commented
Weldone @HalimahOladimeji The input field on the footer for the mobile view looks very small. You should adjust it.

2020-12-04 14:49 UTC, HalimahOladimeji commented
I have corrected it.

2020-12-04 15:36 UTC, Ireti203 commented on submissions/CSS/contactus.html
> +        <div class="firstc">
Kindly change this class name to a more descriptive name

2020-12-04 15:52 UTC, HalimahOladimeji commented
Done.

2020-12-07 10:07 UTC, adaugochi requested changes

2020-12-07 10:07 UTC, adaugochi commented on submissions/CSS/contactus.css
> +body {
Kindly move this `CSS` folder and its contents inside your name folder. It shouldn't be inside the `submissions` folder

2020-12-07 10:07 UTC, adaugochi commented on submissions/CSS/contactus.html
> +<!DOCTYPE html>
This should be inside `html-forms` folder

2020-12-07 14:15 UTC, HalimahOladimeji commented
I've changed the locations of the files.

2020-12-08 07:35 UTC, closed without merging