[143]Develop a Contact Form Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #248
Opened 2020-12-08 15:55 UTC by Nelyne

![Annotation 2020-12-07 135314](https://user-images.githubusercontent.com/54291845/101506691-f3d96680-3975-11eb-831e-bc914e80ed23.png)

2020-12-09 12:07 UTC, Ireti203 requested changes
Remove the spaces in your image names. You already have a product page, you don't have to create another one.

2020-12-09 13:46 UTC, Nelyne commented
> Remove the spaces in your image names. You already have a product page, you don't have to create another one.

I think you are looking at the wrong codes, there aren't any images in the new PR I posted. The previous PR I submitted had images and I closed that PR and created a new one which are the initial codes you'll find and not the ones beneath. Kindly recheck, thank you

2020-12-11 09:03 UTC, Ireti203 requested changes

2020-12-11 09:03 UTC, Ireti203 commented on submissions/nkeirukaEnendu/HTML-Forms/index.html
> +       <img src="./img - Copy/Rectangle 11.png" alt="">
The image name here Rectangle 11.png is not properly written. Remove the spaces in the image name. Also, your product page task has been merged earlier, you dont have to repeat it in this new Pull request.

2020-12-19 10:15 UTC, adaugochi requested changes
Remove spaces from your images names

2021-01-27 09:10 UTC, adaugochi commented
Kindly update your PR title to the new task title that is on the app. Going forward, I will have to close this PR so you can then create a new one

2021-01-27 09:10 UTC, closed without merging