[148] Add Page Navigation to your Pages- Fullstack #31
Dufuna-CodeCamp/Dufuna-Fem pull request #249
Opened 2020-12-08 16:02 UTC by Mayowa2020

Addition of Navigation links  to my  Product Description and Contact Form Pages

![Screenshot (136)](https://user-images.githubusercontent.com/73591664/101507702-23d53980-3977-11eb-968a-4783b6dcf8d9.png)
![Screenshot (137)](https://user-images.githubusercontent.com/73591664/101507713-259efd00-3977-11eb-9a1d-378b565464fd.png)

2020-12-09 12:14 UTC, Ireti203 requested changes
You have not added navigation to your pages. You already have the contact-us and product page before. All you need to do is to link them to each other, such that when I click on "Product page" , it takes me to the product page view. Same for contact us as well...

2020-12-09 19:29 UTC, Mayowa2020 commented
![Screenshot (142)](https://user-images.githubusercontent.com/73591664/101677725-3de94780-3a5d-11eb-8754-d90612a606bc.png)
![Screenshot (143)](https://user-images.githubusercontent.com/73591664/101677732-404ba180-3a5d-11eb-9b99-615b3a30f945.png)

2020-12-09 19:36 UTC, Mayowa2020 commented
The Navigation tab has been included in both to pages as instructed. Please review again.

2020-12-11 11:31 UTC, Ireti203 approved these changes

2020-12-11 11:31 UTC, merged