[138] Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #25
Opened 2020-11-12 20:21 UTC by OluwaboriShobayo

2020-11-12 20:28 UTC, OluwaboriShobayo commented
![image](https://user-images.githubusercontent.com/74042089/98992605-ad871800-252d-11eb-8a25-e5b80c2cbfe5.png)
![image](https://user-images.githubusercontent.com/74042089/98992667-bf68bb00-252d-11eb-8854-5c59cec9d5a8.png)

2020-11-13 09:52 UTC, Ireti203 requested changes

2020-11-13 09:52 UTC, Ireti203 commented on submissions/oluwaboriShobayo/HTML/productPage.html
> +
Remove whitespace

2020-11-13 09:52 UTC, Ireti203 commented on submissions/oluwaboriShobayo/HTML/productPage.html
> +    <head>
Kindly format properly.

2020-11-13 09:52 UTC, Ireti203 commented on submissions/oluwaboriShobayo/HTML/productPage.html
> +    </head>
Here too.

2020-11-13 09:52 UTC, Ireti203 commented on submissions/oluwaboriShobayo/HTML/productPage.html
> +        <a href="#">Home</a>
You should have a list in your nav tag.

2020-11-13 09:52 UTC, Ireti203 commented on submissions/oluwaboriShobayo/HTML/productPage.html
> +
Remove whitespace

2020-11-13 09:52 UTC, Ireti203 commented on submissions/oluwaboriShobayo/HTML/productPage.html
> +
Remove whitespace.

2020-11-13 09:52 UTC, Ireti203 commented on submissions/oluwaboriShobayo/HTML/productPage.html
> +
Remove whitespace.

2020-11-13 12:13 UTC, Ireti203 approved these changes

2020-11-13 12:13 UTC, merged