[160] Create & Style the Customer Signup Page using CSS
Dufuna-CodeCamp/Dufuna-Fem pull request #252
Opened 2020-12-08 20:25 UTC by HalimahOladimeji

Laptop view
![Screenshot 2020-12-08 192700](https://user-images.githubusercontent.com/73618133/101535700-542dcf80-3999-11eb-9983-c056da7dabfd.png)
![Screenshot 2020-12-08 192744](https://user-images.githubusercontent.com/73618133/101535741-660f7280-3999-11eb-934e-b27e7730c14f.png)
Tablet view
![Screenshot 2020-12-08 192520](https://user-images.githubusercontent.com/73618133/101536020-bab2ed80-3999-11eb-8bac-c71fd8334157.png)
![Screenshot 2020-12-08 192602](https://user-images.githubusercontent.com/73618133/101536047-c6061900-3999-11eb-8076-058173ae9110.png)
Mobile view
![Screenshot 2020-12-08 203601](https://user-images.githubusercontent.com/73618133/101536136-e1712400-3999-11eb-8b94-94af81428b4c.png)
![Screenshot 2020-12-08 212342](https://user-images.githubusercontent.com/73618133/101537402-b2f44880-399b-11eb-9dd0-f836ecc2e6d2.png)
![Screenshot 2020-12-08 211456](https://user-images.githubusercontent.com/73618133/101536586-7ecc5800-399a-11eb-987e-7c91efa54f81.png)

2020-12-09 12:19 UTC, Ireti203 commented on submissions/HalimahOladimeji/HTML-forms/signup.html
> +            <p>Registering an account gives you<br>access to sweet promo and events<br>available to only
Remove the breaks. Style with CSS

2020-12-09 12:36 UTC, HalimahOladimeji commented
Corrected. 
![Screenshot 2020-12-09 133258](https://user-images.githubusercontent.com/73618133/101630643-74a26c00-3a23-11eb-9344-196e933194db.png)

2020-12-09 12:37 UTC, Ireti203 requested changes
Avoid usings breaks on your html file. Use CSS to style instead. Check for places where you used breaks and make corrections.

2020-12-09 12:47 UTC, HalimahOladimeji commented
Noted ma. I have removed the breaks in the form too.
![Screenshot 2020-12-09 134556](https://user-images.githubusercontent.com/73618133/101631692-0ced2080-3a25-11eb-8a7a-2a8b16dbdf61.png)

2020-12-10 11:05 UTC, Ireti203 approved these changes

2020-12-10 11:05 UTC, merged