[197] The Software Developer Conditionals - Mobile #181
Dufuna-CodeCamp/Dufuna-Fem pull request #254
Opened 2020-12-08 22:47 UTC by rubyade

Please find the first Java task for review

2020-12-09 12:34 UTC, Ireti203 commented
Add a screenshot of the output on your console.

2020-12-09 12:53 UTC, rubyade commented
![IMAG1645](https://user-images.githubusercontent.com/73884443/101631874-5b022400-3a25-11eb-95ee-8a91c65c5f31.jpg)


> Add a screenshot of the output on your console.

A screenshot has been added. Many thanks.

2020-12-10 09:48 UTC, Ireti203 commented
Your screenshots are not usually clear. You can use Alt + PrtScn to take a screenshot if you are using Windows.

2020-12-10 09:55 UTC, Ireti203 requested changes

2020-12-10 09:55 UTC, Ireti203 commented on javaScript/conditionals.html
> +    <script src="conditionals.js"></script>
Your script should be placed after the closing of the body tag and not in the head tag.

2020-12-10 10:07 UTC, Ireti203 commented on javaScript/conditionals.js
> +    } if (str / 5 === 0) {
Write the next statement on the next line. Also you dont have to keep repeating "if", you can use "else if"

2020-12-10 10:07 UTC, Ireti203 commented on javaScript/conditionals.js
> +    } if (str / 3 === 0 && str / 5 === 0); {
Same here

2020-12-10 13:49 UTC, Ireti203 approved these changes

2020-12-10 13:49 UTC, merged