[148] Add Page Navigation to your pages
Dufuna-CodeCamp/Dufuna-Fem pull request #303
Opened 2020-12-15 13:35 UTC by Posannie

![Screenshot (113)](https://user-images.githubusercontent.com/73827176/102221605-9d72a780-3ee2-11eb-95c3-4795776c733d.png)
![Screenshot (112)](https://user-images.githubusercontent.com/73827176/102221671-b5e2c200-3ee2-11eb-917f-145378f8b454.png)

2020-12-15 14:13 UTC, Ireti203 requested changes

2020-12-15 14:13 UTC, Ireti203 commented on submissions/divineOmozokpia/HTML-Forms/contactpage.html
> +                <li><a href="../html-forms/contactpage.html">Contact Us</a></li>
Your folder name is HTML-Forms. whereas you are using html-forms in the link. Are you sure it is redirecting correctly?

2020-12-16 06:24 UTC, Posannie commented
Yes, it is. 




On Tuesday, December 15, 2020, 3:14 PM, Ireti203 <notifications@github.com> wrote:




@Ireti203 requested changes on this pull request.

In submissions/divineOmozokpia/HTML-Forms/contactpage.html:
> @@ -5,6 +5,13 @@
         <title>Contact Form</title>
     </head>
     <body>
+        <nav>
+            <ul>
+                <li><a href="../HTML/product.html">Product</a></li>
+                <li><a href="../html-forms/contactpage.html">Contact Us</a></li>

Your folder name is HTML-Forms. whereas you are using html-forms in the link. Are you sure it is redirecting correctly?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-16 15:21 UTC, Ireti203 approved these changes

2020-12-16 15:21 UTC, merged