[156]Style the Contact Us Page using CSS -Frontend
Dufuna-CodeCamp/Dufuna-Fem pull request #309
Opened 2020-12-16 13:46 UTC by Lillian-1

![Screenshot 2020-12-16 143105](https://user-images.githubusercontent.com/61032437/102356334-eddd1a00-3f61-11eb-8edd-96d16f19d3de.png)
![Screenshot 2020-12-16 143136](https://user-images.githubusercontent.com/61032437/102356342-f03f7400-3f61-11eb-8e04-ce0c56912f47.png)
![Screenshot 2020-12-16 143236](https://user-images.githubusercontent.com/61032437/102356355-f46b9180-3f61-11eb-95a4-e2f6429cbe92.png)
![Screenshot 2020-12-16 143301](https://user-images.githubusercontent.com/61032437/102356373-f897af00-3f61-11eb-8c1c-19b2db01a66d.png)
![Screenshot 2020-12-16 143326](https://user-images.githubusercontent.com/61032437/102356399-00575380-3f62-11eb-8a25-140932b231bb.png)
![Screenshot 2020-12-16 143352](https://user-images.githubusercontent.com/61032437/102356415-03524400-3f62-11eb-8674-604ef5d0426e.png)
![Screenshot 2020-12-16 143409](https://user-images.githubusercontent.com/61032437/102356424-064d3480-3f62-11eb-9b1b-562ab03ad82c.png)

2020-12-16 14:09 UTC, Ireti203 requested changes
You have 2 contact.html files. One in the html folder and the other in the html-forms folder. Kindly remove the one that is not being used.

2020-12-16 14:09 UTC, Ireti203 commented on submissions/lillianNwaoha/html/contact.html
> +       </form>
Remove the breaks in your code, style With CSS instead

2020-12-16 14:10 UTC, Ireti203 commented
The logo on the navbar for laptop view looks quite distant from the right end of the navbar. Kindly adjust this in your styling.

2020-12-16 16:37 UTC, Lillian-1 commented
Done


Sent from Yahoo Mail for iPhone


On Wednesday, December 16, 2020, 3:11 PM, Ireti203 <notifications@github.com> wrote:




The logo on the navbar for laptop view looks quite distant from the right end of the navbar. Kindly adjust this in your styling.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-19 10:10 UTC, adaugochi approved these changes

2020-12-19 10:10 UTC, merged