[142] Develop a Contact Form Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #321
Opened 2020-12-18 10:30 UTC by RafiatAmin

![Screen Shot 2020-12-03 at 10 36 33 AM](https://user-images.githubusercontent.com/46797474/102604444-79060d80-4124-11eb-99d3-85999ce58fac.png)

2020-12-18 16:05 UTC, Ireti203 requested changes
You have 2 contact.html files. You have one in the HTML folder and another in the html-forms folder. Kindly remove one of these files, you only need one.

2020-12-18 16:20 UTC, RafiatAmin commented
I have sent a screenshot of my folder already. There’s nothing I can do again. Just pick the one that works. Over a month now. I just want to continue my course please.

2020-12-19 10:08 UTC, adaugochi requested changes
So locate this `.DS_Store` inside this path and remove it as well. It is not supposed to be part of your PR
![image](https://user-images.githubusercontent.com/43061141/102686827-838ada80-41ea-11eb-9c59-07249d594976.png)

2020-12-19 10:08 UTC, adaugochi commented on submissions/rafiatAminu/HTML/html-forms/contact.html
> +<!DOCTYPE html>
Well done on the work so far

Moving forward, you have to remove the file. It is not supposed to be here. You already have it inside the correct folder. So delete this one

2021-01-11 14:05 UTC, closed without merging