Printing Product Price with JavaScript
Dufuna-CodeCamp/Dufuna-Fem pull request #329
Opened 2020-12-20 00:30 UTC by misturaeneeolah

2020-12-20 10:43 UTC, TundeOladejo reviewed
It seems you forgot to add the task id to the title and remember to specify the track you are working on also.

2020-12-20 10:43 UTC, TundeOladejo commented on submissions/masturohAl-Ameen/javaScript/printingProductPrice.js
> +
Remove space here

2020-12-20 10:43 UTC, TundeOladejo commented on submissions/masturohAl-Ameen/javaScript/printingProductPrice.js
> +
Here too

2020-12-20 10:48 UTC, TundeOladejo requested changes

2020-12-20 10:48 UTC, TundeOladejo commented on submissions/masturohAl-Ameen/javaScript/printingProductPrice.js
> +
Remove space here too

2020-12-21 06:06 UTC, misturaeneeolah commented
Thank you very much. I will make the necessary corrections now.

2020-12-21 06:56 UTC, closed without merging