[159] Create & Style the Customer Signup Page using CSS -Frontend
Dufuna-CodeCamp/Dufuna-Fem pull request #330
Opened 2020-12-20 21:53 UTC by Immaculeta1

created and styled signup page

2020-12-20 21:57 UTC, Immaculeta1 commented
![Capture1](https://user-images.githubusercontent.com/74491329/102725387-a2868b00-4316-11eb-89a1-7aad33aa6c0d.PNG)
![Capture2](https://user-images.githubusercontent.com/74491329/102725389-a4e8e500-4316-11eb-84e8-b3cb812f7806.PNG)

2020-12-21 08:56 UTC, ToluAkin requested changes

2020-12-21 08:56 UTC, ToluAkin commented on submissions/nwokejeme-immaculeta/html-forms/homepage.html
> +                    <label for="firstName">First Name</label>
@Immaculeta1 Remove all `br` elemenets in this file and style it with css

2020-12-21 08:56 UTC, ToluAkin commented on submissions/nwokejeme-immaculeta/html-forms/homepage.html
> +                    <input type="text" name="firstName" id="firstName" maxlength="50">
There is no need to add text limit to your input field. That should come in when validating the form @Immaculeta1

2020-12-23 13:11 UTC, adaugochi requested changes

2020-12-23 13:11 UTC, adaugochi commented on submissions/nwokejeme-immaculeta/html-forms/homepage.html
> +<html>
Why is this file called `homepage.html`? thought this is signup page. 

Same applies to the css file name

2020-12-26 14:29 UTC, adaugochi approved these changes

2020-12-26 14:31 UTC, adaugochi commented
Send a screenshot of the mobile view of what you dis

2020-12-26 18:40 UTC, Immaculeta1 commented
![Capture2](https://user-image
![Capture3](https://user-images.githubusercontent.com/74491329/103157340-24146800-47b2-11eb-8cf7-7e3aed5a340f.PNG)
s.githubusercontent.com/74491329/103157336-19f26980-47b2-11eb-8db5-5cd0408cda5b.PNG)
![Capture1](https://user-images.githubusercontent.com/74491329/103157338-1c54c380-47b2-11eb-8bed-37495cb3e491.PNG)

2020-12-28 10:44 UTC, adaugochi requested changes

2020-12-28 10:44 UTC, adaugochi commented on submissions/nwokejeme-immaculeta/html-forms/signup.html
> +    <script src="../domManipulation/signUp.js"></script>
Have you gotten to javaScript yet? How come you have these js files

2020-12-30 08:39 UTC, adaugochi approved these changes

2020-12-30 08:52 UTC, adaugochi commented
Well done @Immaculeta1 

Kindly rework your newsletter email input field to look more better
![image](https://user-images.githubusercontent.com/43061141/103340558-a50a8280-4a84-11eb-96c7-70b2160df492.png)

2021-01-02 13:24 UTC, merged