[159] Create and Style the Customer Signup page using CSS
Dufuna-CodeCamp/Dufuna-Fem pull request #336
Opened 2020-12-21 11:04 UTC by lorlahdey

![Capture19](https://user-images.githubusercontent.com/19871450/102770474-83bedd80-4384-11eb-8cee-a109de6e4ffe.PNG)
![Capture20](https://user-images.githubusercontent.com/19871450/102770484-87eafb00-4384-11eb-9841-b06522a97e7f.PNG)
![Capture21](https://user-images.githubusercontent.com/19871450/102770495-8cafaf00-4384-11eb-9879-9b4f2c7f6cd9.PNG)
![Capture22](https://user-images.githubusercontent.com/19871450/102770501-8e797280-4384-11eb-9776-090508e4377d.PNG)

2020-12-21 13:18 UTC, ToluAkin requested changes

2020-12-21 13:18 UTC, ToluAkin commented on submissions/lawalLolade/css/contactUs.css
> +    width: 80%;
Use `px` here @lorlahdey

2020-12-21 13:18 UTC, ToluAkin commented on submissions/lawalLolade/css/contactUs.css
> +    padding: 2% 3% 2%;
Use `px` here @lorlahdey

2020-12-21 13:18 UTC, ToluAkin commented on submissions/lawalLolade/css/contactUs.css
> +        margin-left: 0rem;
There is no need to add unit if the value is 0 @lorlahdey

2020-12-21 13:18 UTC, ToluAkin commented on submissions/lawalLolade/css/productPage.css
> +    font-family: 'Montserrat', sans-serif;
Set the font family in the body tag @lorlahdey

2020-12-21 13:18 UTC, ToluAkin commented on submissions/lawalLolade/css/productPage.css
> +* {
Change all % of margin and padding to px @lorlahdey

2020-12-29 19:52 UTC, Ireti203 approved these changes

2021-01-05 21:11 UTC, lorlahdey commented
ToluAkin

2021-01-11 05:36 UTC, lorlahdey commented
@Ireti203

2021-01-12 13:15 UTC, Ireti203 approved these changes

2021-01-12 13:15 UTC, merged