[153] Style the Product Details Page using CSS
Dufuna-CodeCamp/Dufuna-Fem pull request #343
Opened 2020-12-24 01:14 UTC by Mayowa2020

Product page design using css.
![Screenshot (159)](https://user-images.githubusercontent.com/73591664/103048031-9d7f4100-458d-11eb-940d-ab5e9074cbaf.png)
![Screenshot (160)](https://user-images.githubusercontent.com/73591664/103048036-9f490480-458d-11eb-935b-ce89c89c2cb7.png)
![Screenshot (161)](https://user-images.githubusercontent.com/73591664/103048038-9fe19b00-458d-11eb-8478-baf76ae9a89b.png)
![Screenshot (163)](https://user-images.githubusercontent.com/73591664/103048040-a07a3180-458d-11eb-9511-45d81a4aec94.png)
![Screenshot (164)](https://user-images.githubusercontent.com/73591664/103048044-a112c800-458d-11eb-9fd6-ae8b59a54254.png)
![Screenshot (165)](https://user-images.githubusercontent.com/73591664/103048046-a1ab5e80-458d-11eb-810d-c7cc8041ae72.png)

2020-12-26 10:42 UTC, Ireti203 commented
Weldone @Mayowa2020. Kindly resolve the conflicts on this branch

2020-12-26 11:28 UTC, Ireti203 requested changes
You have two separate files for the product page, index.html and product.html. You should remove one of them. The css should be added to the previously existing html file for the product page. You don't have to create a new one.

2020-12-26 11:28 UTC, Ireti203 commented on submissions/BukkyOyetimehin/HTML-Forms/product.html
> +				<li><a href="contact.html">Contact Us</a></li>
You should also have the link to the product page here.

2021-01-05 09:29 UTC, adaugochi commented
You still have a conflict on your PR. Kindly check the pinned message on #git-versioncontrol channel on slack. You will see a post on how to resolve merge conflict

2021-01-07 14:49 UTC, Mayowa2020 commented
> You still have a conflict on your PR. Kindly check the pinned message on #git-versioncontrol channel on slack. You will see a post on how to resolve merge conflict

2021-01-07 15:04 UTC, Mayowa2020 commented
@adaugochi @Ireti203 Based on the comment, kindly confirm if the conflict issue has been resolved.

2021-01-07 15:44 UTC, closed without merging