[190] Research Programming Languages
Dufuna-CodeCamp/Dufuna-Fem pull request #345
Opened 2020-12-26 08:28 UTC by OluwaboriShobayo

2020-12-26 11:47 UTC, Ireti203 reviewed
Why did you include the html file for the product page in this PR?

2020-12-26 12:21 UTC, Ireti203 requested changes

2020-12-26 12:21 UTC, Ireti203 commented on submissions/oluwaboriShobayo/html-forms/contactForm.html
> +<<<<<<< HEAD
Format here properly.

2020-12-26 12:21 UTC, Ireti203 commented on submissions/oluwaboriShobayo/html-forms/contactForm.html
> +=======
And here too

2020-12-26 12:21 UTC, Ireti203 commented on submissions/oluwaboriShobayo/html-forms/contactForm.html
> +>>>>>>> a10c2f42194fb95960a0957007c20a1fbc289106
Same here

2020-12-26 12:21 UTC, Ireti203 commented on submissions/oluwaboriShobayo/html-forms/contactForm.html
> +<<<<<<< HEAD
Same here

2020-12-26 12:21 UTC, Ireti203 commented on submissions/oluwaboriShobayo/html-forms/contactForm.html
> +>>>>>>> a10c2f42194fb95960a0957007c20a1fbc289106
And here

2020-12-26 14:28 UTC, adaugochi requested changes

2020-12-26 14:28 UTC, adaugochi commented on submissions/oluwaboriShobayo/HTML/productPage.html
> +<!DOCTYPE html>
Why are you creating a product page again?

2020-12-26 14:40 UTC, OluwaboriShobayo commented
I'm sorry, It was a mistake o

2020-12-29 19:47 UTC, Ireti203 commented
Kindly resolve the conflicts on this branch.

2021-01-08 10:55 UTC, closed without merging