[137] Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #356
Opened 2020-12-29 16:06 UTC by Kifaayah

This my product page using only HTML

2020-12-30 09:05 UTC, adaugochi requested changes
Remove the `{137}` in your `{137}productpage.html` file name

2020-12-30 09:05 UTC, adaugochi commented on submissions/jimohKafayat/HTML/{137}productpage.html
> +	<img src="dufuna/images/myimage.PNG" width="400" height="500">
These images used here suppose to be part of your PR. Place these images your `HTML` folder

2020-12-30 16:58 UTC, adaugochi requested changes
Inside the `HTML` folder, create another folder called `images` place the two images you used for this task inside that `images` folder

2020-12-30 16:58 UTC, adaugochi commented on submissions/jimohKafayat/HTML/productpage.html
> +	<img src="dufuna/images/myimage.PNG" width="400" height="500">
This doesn't point to the location of where your images are

2020-12-31 23:04 UTC, Kifaayah commented
The image is in the “images” subfolder inside the dufuna folder in my IDE

Sent from my iPhone

> On 30 Dec 2020, at 5:58 PM, Maryfaith Mgbede <notifications@github.com> wrote:
> 
> @adaugochi requested changes on this pull request.
> 
> Inside the HTML folder, create another folder called images place the two images you used for this task inside that images folder
> 
> In submissions/jimohKafayat/HTML/productpage.html:
> 
> > +	<h2><em>KAHF KOLLECTIONS</e></h2>
> +
> +
> +<nav>
> +	<p>CATEGORIES</p>
> +	<ol>
> +		<li><a href="#">Men Jalabiya</a></li>
> +		<li><a href="#">Dubai Wears</a></li>
> +		<li><a href="#">Women Jalabiya</a></li>
> +		<li><a href="#">Ladies Gowns</a></li>
> +		<li><a href="#">Corporate Wears</a></li>
> +		<li><a href="#">Egyptian Gowns</a></li>
> +		<li><a href="#">Veils/Hijab</a></li>
> +		<li><a href="#">Islamic Kaftans</a></li>
> +	</ol>
> +	<img src="dufuna/images/myimage.PNG" width="400" height="500">
> This doesn't point to the location of where your images are
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-02 13:33 UTC, Ireti203 commented
Create a folder for images in the HTML folder, then change the directory in your code appropriately.

2021-01-06 13:54 UTC, Ireti203 approved these changes

2021-01-06 13:58 UTC, merged