[155] Style the Contact Us Page using CSS
Dufuna-CodeCamp/Dufuna-Fem pull request #372
Opened 2021-01-05 11:31 UTC by Mayowa2020

Updates on the html and addition of new cs
![Screenshot (184)](https://user-images.githubusercontent.com/73591664/103641319-df2ac700-4f51-11eb-8fad-72ac2d1ecdc7.png)
![Screenshot (185)](https://user-images.githubusercontent.com/73591664/103641332-e225b780-4f51-11eb-82f3-32a023d1c1c2.png)
![Screenshot (186)](https://user-images.githubusercontent.com/73591664/103641336-e356e480-4f51-11eb-8be9-c35d52ba0408.png)
![Screenshot (187)](https://user-images.githubusercontent.com/73591664/103641337-e3ef7b00-4f51-11eb-989d-a50bbe044ec8.png)
![Screenshot (188)](https://user-images.githubusercontent.com/73591664/103641338-e4881180-4f51-11eb-82e6-d2065c7b81b6.png)
![Screenshot (189)](https://user-images.githubusercontent.com/73591664/103641340-e520a800-4f51-11eb-85b8-d0de9e31863d.png)

s files for my contact page.

2021-01-05 12:21 UTC, Ireti203 commented
Weldone @Mayowa2020 You currently have an open PR that is yet to be merged. Whenever you have an open PR, It is safer you ensure it gets merged before opening another.

2021-01-08 14:00 UTC, adaugochi requested changes
Remove spaces from images name e.g `facebook logo.jpg, facebook logo.png, gmail logo.png, gmail logo.jpg` etc. Also, these images appear twice, the differences in the extension(png or jpg). why not just use one of them and remove the rest.

Meanwhile...well done. Keep up with the good work

2021-01-08 14:00 UTC, adaugochi commented
Remove everything pertaining to product on this PR

2021-01-08 22:56 UTC, Mayowa2020 commented on submissions/BukkyOyetimehin/HTML-Forms/contact.html
> -    </form>
This is not part of the file.

2021-01-12 09:58 UTC, Ireti203 approved these changes

2021-01-12 10:06 UTC, merged