[159]Create & Style the Customer Signup Page using CSS-Frontend
Dufuna-CodeCamp/Dufuna-Fem pull request #392
Opened 2021-01-07 15:52 UTC by mutmainaho

![screencapture-127-0-0-1-8080-html-forms-signup-html-2021-01-07-16_47_52](https://user-images.githubusercontent.com/66721821/103913251-a3862d80-5108-11eb-8800-476ce92ad07e.png)
![screencapture-127-0-0-1-8080-html-forms-signup-html-2021-01-03-13_41_41](https://user-images.githubusercontent.com/66721821/103913280-aa14a500-5108-11eb-9333-77fe643bfc23.png)
![screencapture-127-0-0-1-8080-html-forms-signup-html-2021-01-03-13_42_00](https://user-images.githubusercontent.com/66721821/103913299-aed95900-5108-11eb-93b4-c3db491612dc.png)

2021-01-07 23:24 UTC, Ireti203 commented
The font size on mobile looks too big. Kindly reduce it.

2021-01-07 23:57 UTC, Ireti203 requested changes

2021-01-07 23:57 UTC, Ireti203 commented on submissions/MutmainahOdunewu/html-forms/signup.html
> +
Remove whitespace

2021-01-07 23:57 UTC, Ireti203 commented on submissions/MutmainahOdunewu/html-forms/signup.html
> +          <button type="submit" id="bttn">SIGN UP</button>
This should be under the form tag, format properly. Also, remove the breaks and style with css instead.

2021-01-07 23:57 UTC, Ireti203 commented on submissions/MutmainahOdunewu/html-forms/signup.html
> +
Remove whitespace

2021-01-07 23:57 UTC, Ireti203 commented on submissions/MutmainahOdunewu/html-forms/signup.html
> +        <ul class="look">
Kindly use a more descriptive naming for the class.

2021-01-08 08:54 UTC, adaugochi commented
According to the mockup, the label i.e `first name, last name` etc are not aligned to the centre. Kindly change that to align left

2021-01-08 09:28 UTC, closed without merging