[264] Querying the Transportation Database
Dufuna-CodeCamp/Dufuna-Fem pull request #397
Opened 2021-01-08 10:31 UTC by modupeadeonojobi

Add transportation query file

2021-01-08 13:52 UTC, adaugochi requested changes

2021-01-08 13:52 UTC, adaugochi commented on submissions/modupeAdeOnojobi/database/transportationQuery.sql
> +// 424
The total number of record is `891` it means when you add `290 + 424`, you ought to have `891` in total. Kindly rerun your query. drop the database, run the query that creates the database and tables again. Then import the passengers CSV file first, then travel detail, before the survival file.

2021-01-08 13:52 UTC, adaugochi commented on submissions/modupeAdeOnojobi/database/transportationQuery.sql
> +1. SELECT survived, COUNT(*) FROM accidents WHERE survived = 1 GROUP BY survived;
Just do `SELECT COUNT(*)`. I don't see the reason you are selecting `survived`

2021-01-08 13:52 UTC, adaugochi commented on submissions/modupeAdeOnojobi/database/transportationQuery.sql
> +// 9
This is correct

2021-01-08 13:52 UTC, adaugochi commented on submissions/modupeAdeOnojobi/database/transportationQuery.sql
> +	AND trips.number_of_siblings_spouses_aboard > 0 passengers.age > 35;
There is an error here `trips.number_of_siblings_spouses_aboard > 0 passengers.age > 35`

2021-01-08 13:52 UTC, adaugochi commented on submissions/modupeAdeOnojobi/database/transportationQuery.sql
> +4. SELECT COUNT(*), accidents.survived, trips.point_of_embarkation FROM accidents LEFT JOIN trips
You are only asked to `count` here. This other columns `accidents.survived, trips.point_of_embarkation`, you weren't ask too

2021-01-08 13:52 UTC, adaugochi commented on submissions/modupeAdeOnojobi/database/transportationQuery.sql
> +3. SELECT P.full_name, P.sex, P.age, T.point_of_embarkation FROM passengers AS P LEFT JOIN trips AS T
You were only ask to do `P.full_name, P.sex`

2021-01-11 16:07 UTC, Ireti203 approved these changes

2021-01-11 16:07 UTC, merged