[222] Sign-Up Form Validation - Mobile
Dufuna-CodeCamp/Dufuna-Fem pull request #411
Opened 2021-01-11 10:28 UTC by HalimahOladimeji

![Screenshot 2021-01-10 200521](https://user-images.githubusercontent.com/73618133/104169517-fceba680-53ff-11eb-99d4-2bbcfcfedf28.png)

2021-01-11 10:58 UTC, adaugochi requested changes
Well done. 

The function `firstNameFieldValidation, lastNameFieldValidation` etc literally does the same thing. Why not create a single function for that and pass the things that make them different as a parameter.

Also, I thing you should check if the input field is empty first before checking for if it matches the regex

2021-01-11 10:58 UTC, adaugochi commented on submissions/HalimahOladimeji/HTML-forms/contactus.html
> -<!DOCTYPE html>
Is there a reason why you are deleting this file

2021-01-11 10:58 UTC, adaugochi commented on submissions/HalimahOladimeji/CSS/contactus.css
> -body {
Is there a reason why you are deleting this file

2021-01-11 13:29 UTC, HalimahOladimeji commented
I deleted the contact us files because it has been validated and i intend to upload it in my next PR. I hope that is okay.

2021-01-12 08:56 UTC, adaugochi commented
> I deleted the contact us files because it has been validated and I intend to upload it in my next PR. I hope that is okay.

it is not that okay. Even if you intend to change it, you should have waited still then. I will advise you revert the changes back.

2021-01-12 11:36 UTC, adaugochi approved these changes
Well done

2021-01-12 11:36 UTC, merged