[142] Develop a Contact Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #413
Opened 2021-01-11 11:22 UTC by Kifaayah

![Annotation 2021-01-11 121743](https://user-images.githubusercontent.com/75373538/104176494-9ff3ee80-5407-11eb-9d7d-ab6a2f4cae00.png)

2021-01-11 15:45 UTC, Ireti203 requested changes

2021-01-11 15:45 UTC, Ireti203 commented on submissions/jimohKafayat/html-forms/contactform.html
> +
Remove whitespaces

2021-01-11 15:45 UTC, Ireti203 commented on submissions/jimohKafayat/html-forms/contactform.html
> +
Same here

2021-01-11 15:45 UTC, Ireti203 commented on submissions/jimohKafayat/html-forms/contactform.html
> +
Remove whitespaces

2021-01-11 15:46 UTC, Ireti203 commented
You are to attach the screenshot of the page on your browser. Not screenshot of github...

2021-01-13 09:21 UTC, adaugochi requested changes

2021-01-13 09:21 UTC, adaugochi commented on submissions/jimohKafayat/HTML/productpage.html
> +		<a href="../html-forms/contactform.html">Contact Us</a>
This navigation links you added here is for your next task. if you add it now you won't have anything to do for the next task and you won't be able to proceed. Kindly remove them for now

2021-01-13 09:21 UTC, adaugochi commented on submissions/jimohKafayat/html-forms/contactform.html
> +        <a href = "contactform.html"> Contact Us </a>
Same here too

2021-01-13 09:21 UTC, adaugochi commented on submissions/jimohKafayat/html-forms/contactform.html
> +	    <a href = "../HTML/productpage.html"> Product Page </a>
And here

2021-01-13 09:21 UTC, adaugochi commented on submissions/jimohKafayat/HTML/productpage.html
> +		<a href="productpage.html">Product Page</a>
same here

2021-01-14 09:28 UTC, adaugochi approved these changes

2021-01-14 09:28 UTC, merged