[104] Research Programming Languages
Dufuna-CodeCamp/Dufuna-Fem pull request #415
Opened 2021-01-11 16:20 UTC by Blessing-Hubb

#Task: Research programming languages
I have added link to spreadsheet in appropriate folder

2021-01-12 08:47 UTC, adaugochi requested changes
Kindly grant me access to your sheet

Also, remove spaces in folders or file names

2021-01-13 11:37 UTC, Ireti203 requested changes
This PR ought to include only the .txt file containing the link, but you have also pushed some images in the HTML folder. Kindly rectify this.

2021-01-13 12:28 UTC, Blessing-Hubb commented
Rectification done

2021-01-13 14:55 UTC, adaugochi approved these changes

2021-01-13 14:56 UTC, merged