[153] Style the Product Details Page using CSS-Fullstack
Dufuna-CodeCamp/Dufuna-Fem pull request #432
Opened 2021-01-14 10:48 UTC by Constancia2

![Desktopview 1](https://user-images.githubusercontent.com/74066153/104581038-53562080-565e-11eb-9342-3ccf07513674.png)
![desktopview 2](https://user-images.githubusercontent.com/74066153/104581041-54874d80-565e-11eb-9f66-42f8dc4e5beb.png)
![mobile view 1](https://user-images.githubusercontent.com/74066153/104581081-60730f80-565e-11eb-924a-9a150b58298e.png)
![mobileview 2](https://user-images.githubusercontent.com/74066153/104581088-61a43c80-565e-11eb-9bd9-6167c3eb02a6.png)
![mobileview 3](https://user-images.githubusercontent.com/74066153/104581096-64069680-565e-11eb-8dc0-cfbbaccbe334.png)

2021-01-14 11:13 UTC, Ireti203 commented
Kindly close this PR and create a new one using the title on the app

2021-01-14 11:34 UTC, Ireti203 requested changes

2021-01-14 11:34 UTC, Ireti203 commented on submissions/OnyediriConstancia/HTML/index.html
> +
Remove whitespace

2021-01-14 11:34 UTC, Ireti203 commented on submissions/OnyediriConstancia/HTML/index.html
> +
Remove whitespace

2021-01-14 11:34 UTC, Ireti203 commented on submissions/OnyediriConstancia/HTML/index.html
> +
Remove whitespace

2021-01-15 09:13 UTC, adaugochi commented
@Constancia2 on the **Dufuna app**, is this ` [153] Style the Product Details Page using CSS-Fullstack` what is showing as your task title?

2021-01-15 10:04 UTC, closed without merging