[DFMD-7] Style the Product Details Page using CSS
Dufuna-CodeCamp/Dufuna-Fem pull request #438
Opened 2021-01-18 13:46 UTC by wuhmi

![CSS1a](https://user-images.githubusercontent.com/62771719/104923003-bec02b00-599b-11eb-9960-1d8c6210da30.jpg)
![CSS1b](https://user-images.githubusercontent.com/62771719/104923033-c97ac000-599b-11eb-90f3-3b55c3738322.jpg)
![CSS1c](https://user-images.githubusercontent.com/62771719/104923059-d3042800-599b-11eb-89f0-b73074ccfe12.jpg)
![CSSTabletview](https://user-images.githubusercontent.com/62771719/104923088-dc8d9000-599b-11eb-9195-04fadb40c842.jpg)

2021-01-25 09:00 UTC, adaugochi commented
Well dome. Kindly send a mobile screenshot of your work

2021-02-02 14:16 UTC, TundeOladejo requested changes

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.FOOTER {
This should not be in block/capital letters.

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.Specs {
Your class naming should start with a small letter

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.IMG1,
It's not a good practice to use uppercase in your naming convention. I think you should also use something more descriptive for your selectors.

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.IMG1,
It's not a good practice to use uppercase in your naming convention. I think you should also use something more descriptive for your selectors.

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.Specs {
Your class naming should start with a small letter

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.FOOTER {
This should not be in block/capital letters.

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.EG {
Same here hoo

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +img.GEL {
Here too

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +    .IMG3 {
Here too

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.FOOTER {
This should not be in block/capital letters.

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.Specs {
Your class naming should start with a small letter

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +#Quantity {
same here too

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.IMG3 {
It's not a good practice to use uppercase in your naming convention. I think you should also use something more descriptive for your selectors.

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.EG {
Same goes here too

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +img.GEL {
Here too

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +    .IMG3 {
Here too

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/HTML/productpage.html
> +        <div class="nav bar">
`bar` was not used anywhere in your CSS code.

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/HTML/productpage.html
> +        <img class="SHMPOO" src="Images/N-SHAMPOO.jpg" controls></Images>
Please ensure you use a proper naming convention for your classes.

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/HTML/productpage.html
> +                <strong class="QTY">Quantity:</strong>
Same here too

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/HTML/productpage.html
> +                    <img class="SOIL" src="Images/S-OIL.jpg" controls>
Here too

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/HTML/productpage.html
>  <!DOCTYPE html>
Please take time to make corrections and changes to this HTML file

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/html-forms/productpage.html
> +            <h4><strong>PRODUCT DESCRIPTION</strong></h4>
An `h` tag cannot go inside a `p` tag. Kindly separate them.

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/html-forms/productpage.html
> +        </div>
Format properly

2021-02-02 14:16 UTC, TundeOladejo commented on submissions/omawumiRebeccaMoju/html-forms/productpage.html
>  <!DOCTYPE html>
Change the name of this file to something else. You already have a file with that name already

2021-02-04 12:01 UTC, wuhmi commented
![MOBILE1](https://user-images.githubusercontent.com/62771719/106889236-05c25600-66e8-11eb-99be-0d16ee7cbaa5.jpg)
![MOBILE 2](https://user-images.githubusercontent.com/62771719/106889399-3dc99900-66e8-11eb-9746-2d605de14ec8.jpg)
![MOBILE 3](https://user-images.githubusercontent.com/62771719/106889561-75384580-66e8-11eb-93ab-78cfec5d6d76.jpg)
![MOBILE 4](https://user-images.githubusercontent.com/62771719/106889666-a153c680-66e8-11eb-9888-31d93a184e30.jpg)
![MOBILE 5](https://user-images.githubusercontent.com/62771719/106889849-dd872700-66e8-11eb-92df-219339a16f83.jpg)

2021-02-04 15:21 UTC, wuhmi commented
![MOBILE 4](https://user-images.githubusercontent.com/62771719/106913837-b8081680-6704-11eb-8634-262dbe01599f.jpg)
![MOBILE 5](https://user-images.githubusercontent.com/62771719/106914064-f0a7f000-6704-11eb-9957-9293a466cc77.jpg)

2021-02-09 09:07 UTC, adaugochi requested changes

2021-02-09 09:07 UTC, adaugochi commented on submissions/omawumiRebeccaMoju/CSS/styleproductpage.css
> +.eg {
These `sl, vm, eg`  are not good class names. Kindly give it a better name. Also, no need to assign different class names. Just give it a single class name and use that class name all other the place you want to use it in your HTML code

2021-02-18 11:31 UTC, Ireti203 approved these changes

2021-02-18 11:31 UTC, merged