[DFFE-11] Sign-Up Form Validation
Dufuna-CodeCamp/Dufuna-Fem pull request #450
Opened 2021-01-19 09:00 UTC by OluwaboriShobayo

2021-01-19 13:55 UTC, OluwaboriShobayo commented
![image](https://user-images.githubusercontent.com/74042089/105043690-1d51db80-5a66-11eb-83b3-40048b281b1f.png)
![image](https://user-images.githubusercontent.com/74042089/105043750-35295f80-5a66-11eb-9503-a07afa955fb7.png)
![image](https://user-images.githubusercontent.com/74042089/105043792-3e1a3100-5a66-11eb-8071-058232435291.png)

2021-01-21 09:29 UTC, adaugochi requested changes
`firstnameValidation, lastnameValidation and so on` function looks similar. Why don't you write a function and check if it is empty and another function if it matches regex.

2021-01-21 12:47 UTC, OluwaboriShobayo commented
![image](https://user-images.githubusercontent.com/74042089/105043690-1d51db80-5a66-11eb-83b3-40048b281b1f.png)
![image](https://user-images.githubusercontent.com/74042089/105043750-35295f80-5a66-11eb-9503-a07afa955fb7.png)
![image](https://user-images.githubusercontent.com/74042089/105043792-3e1a3100-5a66-11eb-8071-058232435291.png)


> `firstnameValidation, lastnameValidation and so on` function looks similar. Why don't you write a function and check if it is empty and another function if it matches regex.

Thank you, but when i tried creating different functions for them, it was not giving me the success criteria. The only criteria that all the fields were fulfilling was the 'Special numbers are not allowed"

2021-01-25 08:58 UTC, adaugochi requested changes

2021-01-25 08:58 UTC, adaugochi commented on submissions/oluwaboriShobayo/DOM/signUp.js
> +}
You are still repeating one thing over and over again. Why don't you write a single function called `emptyField` that take `fieldName` and `errorMessage` as a parameter i.e `emptyField(fieldName, errorMessage, event)`. Then the function will hold this block of code as seen below 
```
if (fieldName.value == '') {
        fieldName.nextElementSibling.innerHTML = errorMessage;
        event.preventDefault();
}
```
Then when calling the function, you can then pass in the argument. E,g for firstname, you can call the function like this `emptyField(firstname, "Please enter your first name")`


Do a similar approach for the regex check

2021-01-25 14:54 UTC, Ireti203 approved these changes

2021-01-25 14:54 UTC, merged