[DFFE-7] Style the Product Details Page using CSS
Dufuna-CodeCamp/Dufuna-Fem pull request #473
Opened 2021-01-21 12:59 UTC by kaozarat16

![phone product page 1](https://user-images.githubusercontent.com/73613335/105354355-bca2da00-5bf0-11eb-8357-084cbebdbf1c.PNG)
![phone product page 2](https://user-images.githubusercontent.com/73613335/105354374-c1678e00-5bf0-11eb-83e2-47c2703f2b20.PNG)
![tab product page 1](https://user-images.githubusercontent.com/73613335/105354390-c75d6f00-5bf0-11eb-8b2a-286f17962341.PNG)
![tab product page 2](https://user-images.githubusercontent.com/73613335/105354402-caf0f600-5bf0-11eb-98cc-82996cba5fde.PNG)
![productpage](https://user-images.githubusercontent.com/73613335/105354413-cdebe680-5bf0-11eb-9542-094363a19c47.PNG)

2021-01-22 10:33 UTC, Ireti203 requested changes
Remove spaces from image names

2021-01-22 10:33 UTC, Ireti203 commented on submissions/kaozaratAmoo/html/Product.html
> +                               <P class ="copy"> Copyright 2020 Agrobay.com.
This should be p and not P

2021-01-22 11:15 UTC, Ireti203 requested changes

2021-01-25 08:51 UTC, adaugochi requested changes
Remove spaces on images names. Replace with `-` or `_`

2021-01-25 08:51 UTC, adaugochi commented on submissions/kaozaratAmoo/html/Product.html
> +                       </footer>
No closing `</body>` tag

2021-01-25 08:51 UTC, adaugochi commented on submissions/kaozaratAmoo/html/Product.html
> +                               <P class ="copy"> Copyright 2020 Agrobay.com.
Also fix this comment by Ireti

2021-01-28 10:28 UTC, Ireti203 approved these changes

2021-01-28 10:28 UTC, merged