[DFMD-3] Develop a Contact Form Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #483
Opened 2021-01-22 10:41 UTC by Aarinolaa

![image](https://user-images.githubusercontent.com/75532208/105481010-bc651600-5ca6-11eb-81f5-013ae08f9721.png)

2021-01-22 11:54 UTC, Aarinolaa commented
The navigation links for Contact form and Product were added to the pages.
![image](https://user-images.githubusercontent.com/75532208/105487420-5bdad680-5cb0-11eb-9d59-3b079fc8fa53.png)
![image](https://user-images.githubusercontent.com/75532208/105487736-e02d5980-5cb0-11eb-9c4f-d1c57122d0d1.png)

2021-01-23 23:24 UTC, Ireti203 requested changes
You have three .html files in the HTML-FORMS folder, 2 of which are not properly named. Remove the two HTML FORM.html files in the HTML-FORMS folder.

2021-01-24 11:30 UTC, Aarinolaa commented
Hello Ireti, thanks for your comment. I am quite confused as to which file to delete because I followed the instructions which said to update the product page in the html folder and then which file do i include html form.
please clarify.
thanks.

2021-01-27 10:18 UTC, Ireti203 approved these changes

2021-01-27 10:19 UTC, merged