[DFMD-4] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-Fem pull request #493
Opened 2021-01-24 12:55 UTC by MoyinoluwaA

2021-01-24 12:55 UTC, MoyinoluwaA commented
![Screenshot (72)](https://user-images.githubusercontent.com/74017674/105630882-cffdb180-5e4b-11eb-9405-c7c29dde342d.png)
![Uploading Screenshot (73).png…]()

2021-01-24 12:58 UTC, MoyinoluwaA commented
![Screenshot (73)](https://user-images.githubusercontent.com/74017674/105630961-29fe7700-5e4c-11eb-8205-ce11ddb476b9.png)

2021-01-24 16:09 UTC, Ireti203 requested changes

2021-01-24 16:09 UTC, Ireti203 commented on submissions/moyinoluwaAdenuga/HTML/index.html
> +            <li><a href="../html-forms/contactform.html">Contact Form</a></li>
You should also have the link to index.html

2021-01-24 18:38 UTC, MoyinoluwaA commented
![Screenshot (74)](https://user-images.githubusercontent.com/74017674/105640002-c4c27a00-5e7b-11eb-9ce6-31ed9a8b3336.png)

2021-01-25 08:44 UTC, adaugochi approved these changes

2021-01-25 08:44 UTC, merged