[DFFE-7] Style the Product Details Page using CSS
Dufuna-CodeCamp/Dufuna-Fem pull request #495
Opened 2021-01-24 23:03 UTC by DeeDeji20

![Web capture_1-1-2021_1544_](https://user-images.githubusercontent.com/64081620/105646525-363b0200-5e55-11eb-9f8c-c2792e3ddad4.jpeg)
![Web capture_1-1-2021_15522_](https://user-images.githubusercontent.com/64081620/105646527-3804c580-5e55-11eb-8671-b8f1a2e524c3.jpeg)
![Web capture_1-1-2021_15441_](https://user-images.githubusercontent.com/64081620/105646528-3935f280-5e55-11eb-8a24-7d44ff21d67c.jpeg)

2021-01-25 08:42 UTC, adaugochi commented
There is conflict on your PR, kindly resolve them

2021-02-02 14:27 UTC, TundeOladejo requested changes

2021-02-02 14:27 UTC, TundeOladejo commented on index.html
> +        </div>
Remove these commented lines

2021-02-02 14:27 UTC, TundeOladejo commented on index.html
> +        <div class="descript">
Your class name is not really cool. You might want to change it.

2021-02-02 14:27 UTC, TundeOladejo commented on index.html
> +            </div>
Format this block of code properly. I think you need to also remove one of those two div elements.

2021-02-12 08:59 UTC, adaugochi requested changes
You push people files along with your task. How can you have `426 File changed`

2021-02-18 10:17 UTC, Ireti203 commented
@DeeDeji20 Kindly resolve the conflicts on this branch

2021-02-25 09:33 UTC, closed without merging