[DFFE-11] Sign-Up Form Validation
Dufuna-CodeCamp/Dufuna-Fem pull request #546
Opened 2021-02-02 10:46 UTC by lorlahdey

@Ireti203

2021-02-02 14:06 UTC, Ireti203 requested changes
I expect to see where the .js file is linked in your signUp.html file but this PR doesnt show that.

2021-02-02 14:06 UTC, Ireti203 commented on submissions/lawalLolade/DOM/signUp.js
> +const signUp = document.getElementById('Form');
This Id is better written as 'form'

2021-02-03 18:56 UTC, lorlahdey commented
@Ireti203

2021-02-04 11:09 UTC, Ireti203 approved these changes

2021-02-04 11:36 UTC, adaugochi requested changes
You didn't write a function to check  if password 1 matches password 2

2021-02-04 21:52 UTC, lorlahdey commented
@adaugochi @Ireti203

2021-02-05 09:34 UTC, Ireti203 approved these changes

2021-02-05 09:34 UTC, merged