[DFFE-2] Develop a Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #568
Opened 2021-02-06 21:38 UTC by cindyemeh

![2](https://user-images.githubusercontent.com/59322633/107130201-842b1d80-68cb-11eb-9880-41df99dc507a.PNG)

![1](https://user-images.githubusercontent.com/59322633/107130254-e6841e00-68cb-11eb-8838-b511cdc3d3cc.PNG)

2021-02-08 09:23 UTC, Ireti203 commented
You should add the screenshot of the webpage you worked on...i.e the product page

2021-02-08 09:36 UTC, Ireti203 requested changes

2021-02-08 09:36 UTC, Ireti203 commented on submissions/cindyEmeh/html/index.html
> +</html>
Why do you have two closing tags for html and body?

2021-02-08 09:36 UTC, Ireti203 commented on submissions/cindyEmeh/html/index.html
> +
Remove whitespace

2021-02-08 09:36 UTC, Ireti203 commented on submissions/cindyEmeh/html/index.html
> +     <div><h3>Yum Spectacles</h3>
I can't see the closing tag of the div you opened here

2021-02-08 09:43 UTC, Ireti203 requested changes

2021-02-08 09:43 UTC, Ireti203 commented on submissions/cindyEmeh/html/index.html
> +  It does not matter if your woman is an introvert, extrovert or ambivert, we have ranges of spectacles to be selected from.</h4>
Format this block of code properly

2021-02-08 09:43 UTC, Ireti203 commented on submissions/cindyEmeh/html/index.html
> +
Remo whitespace

2021-02-08 09:43 UTC, Ireti203 commented on submissions/cindyEmeh/html/index.html
> +         </ol>
Format this block of code properly

2021-02-09 22:15 UTC, cindyemeh commented
Thanks for the review.

I am on it.

On Mon, 8 Feb 2021, 10:43 Ireti203, <notifications@github.com> wrote:

> *@Ireti203* requested changes on this pull request.
> ------------------------------
>
> In submissions/cindyEmeh/html/index.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/568#discussion_r571900919>
> :
>
> > +<h4>Be Spectacled! is your one stop to all types of spectacles that reflect the personality of your woman.
> +  <p>Oh yes, spectacles do reflect personalities! </p>
> +  <p>Are you surprised to hear that?</p>
> +  It does not matter if your woman is an introvert, extrovert or ambivert, we have ranges of spectacles to be selected from.</h4>
>
> Format this block of code properly
> ------------------------------
>
> In submissions/cindyEmeh/html/index.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/568#discussion_r571901355>
> :
>
> > +    <meta charset="UTF-8">
> +       <title>BE SPECTACLED!</title>
> +</head>
> +<body>
> +  <h1>BE SPECTACLED!</h1>
> +
> +<h4>Be Spectacled! is your one stop to all types of spectacles that reflect the personality of your woman.
> +  <p>Oh yes, spectacles do reflect personalities! </p>
> +  <p>Are you surprised to hear that?</p>
> +  It does not matter if your woman is an introvert, extrovert or ambivert, we have ranges of spectacles to be selected from.</h4>
> +
> +    <section>
> +        <h2>Products</h2>
> +        <div><h3>Bae Spectacles</h3>
> +            <img src= "young-teen-woman-sunglasses-hat-holding-shopping-bags-her-hands-feeling-so-happiness-isolated-green-wall.jpg" width="500" height="400"  alt="Sale photo created by diana.grytsku - www.freepik.com">
> +
>
> Remo whitespace
> ------------------------------
>
> In submissions/cindyEmeh/html/index.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/568#discussion_r571903423>
> :
>
> > +       <ol>
> +         <li>Adventurous.</li>
> +         <li>Free-spirited.</li>
> +         <li>Fashionista-in-the-making.</li>
> +         </ol>
>
> Format this block of code properly
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/568#pullrequestreview-585311421>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOETCCNQZHEQCYAYAYQJBY3S56W4JANCNFSM4XGWEUCQ>
> .
>

2021-02-12 23:23 UTC, cindyemeh commented
Kindly review. Changes have been made.
Thank you.

2021-02-15 08:52 UTC, Ireti203 commented
Upload the screenshot of the web page

2021-02-16 13:10 UTC, Ireti203 commented
@cindyemeh You have made the changes rewuested on this PR. You should add, commit and push your changes to the branch.

2021-02-18 10:13 UTC, Ireti203 commented
@cindyemeh You have not made the changes requested on this PR.  You should push your changes to the 'page' branch

2021-02-23 14:51 UTC, Ireti203 approved these changes

2021-02-23 14:51 UTC, merged