[CSFS-111]  Develop a Customer details list view page
Dufuna-CodeCamp/Dufuna-Fem pull request #573
Opened 2021-02-08 22:25 UTC by rubyade

![Screenshot (58)](https://user-images.githubusercontent.com/73884443/107289143-dbb0c100-6a64-11eb-9213-1d0fbac6c28e.png)

2021-02-09 08:54 UTC, adaugochi requested changes

2021-02-09 08:54 UTC, adaugochi commented on submissions/rubyAdeniregun/php/create_table.php
> +    $sql = "CREATE TABLE customer_details(
You are not expected to create a new table. You are to work with the e-commerce database  task you did previously

2021-02-09 10:19 UTC, adaugochi requested changes
Kindly read through the task again. You are not doing what the task required of you

2021-02-10 12:04 UTC, adaugochi requested changes

2021-02-10 12:04 UTC, adaugochi commented on submissions/rubyAdeniregun/php/listview.php
> +try{
This is what looks like what you are asked to do.

But, With the way you implement this, each time I reload this page, this query `"SELECT * FROM customer_details"` will always run. Which is not what we want to do. You have to look for a way to store the result gotten from this query in a cookie. So if cookie is set then you don't want to run the query again but get the data from the cookie store

2021-02-11 09:54 UTC, adaugochi requested changes
You haven't done what is required of you

2021-02-11 10:44 UTC, adaugochi requested changes

2021-02-11 10:44 UTC, adaugochi commented on submissions/rubyAdeniregun/php/load_cookie.php
> +<?php
This file isn't necessary. We ain't doing anything with session

2021-02-11 10:44 UTC, adaugochi commented on submissions/rubyAdeniregun/php/listview.php
> +    if ($result->rowCount() > 0){
Now there is progress

But if I reload this `listview.php` this query (`"SELECT * FROM customer_details"`) will always run. But, that is not what we want. We don't want to always run this query all the time, then store it in a cookie. 

Now. when we reload the `listview.php`, we want `$result` to be that coming from that stored in the cookie as long as the cookie is set. If cookie has expired, then `$result` should be that comming from the query

2021-02-12 07:41 UTC, Ireti203 commented
@rubyade You still haven't made the changes @adaugochi requested in the listview.php file.

2021-02-12 08:54 UTC, adaugochi requested changes

2021-02-12 08:54 UTC, adaugochi commented on submissions/rubyAdeniregun/php/listview.php
> +setcookie("name", "Customer Details", time()+3600, "/", "", false);
This isn't doing anything

2021-02-12 08:54 UTC, adaugochi commented on submissions/rubyAdeniregun/php/listview.php
> +    if ($result->rowCount() > 0){
The idea is to store the `$result` gotten from the query in a cookie. This action should be within a function.

Now. when we reload the `listview.php`, we want `$result` to be that coming from that stored in the cookie as long as the cookie is set. If the cookie has expired, then `$result` should be that coming from the query

2021-02-15 13:19 UTC, rubyade reviewed
![Screenshot (60)](https://user-images.githubusercontent.com/73884443/107951554-d38edf00-6f98-11eb-816b-2d0e7868aeee.png)

2021-02-15 14:12 UTC, merged