[DFFS-37] Database Design For A Transportation Company
Dufuna-CodeCamp/Dufuna-Fem pull request #603
Opened 2021-02-16 03:14 UTC by TunrayoIlawole

Added database for a transportation company.

2021-02-16 09:01 UTC, Ireti203 requested changes

2021-02-16 09:01 UTC, Ireti203 commented on submissions/motunrayoIlawole/Database/transportation.sql
> +    age INT,
Kindly uses "varchar" here

2021-02-16 12:14 UTC, TunrayoIlawole commented on submissions/motunrayoIlawole/Database/transportation.sql
> +    age INT,
For the age?

2021-02-16 12:24 UTC, adaugochi requested changes

2021-02-16 12:24 UTC, adaugochi commented on submissions/motunrayoIlawole/Database/transportation.sql
> +    age INT,
Yes

2021-02-17 09:07 UTC, adaugochi commented
@TunrayoIlawole are you such you made any changes? it didn't reflect on your PR

2021-02-17 09:10 UTC, closed without merging