[CSFS-112] Develop a List View for Customer Orders And Store The Data in A Cookie
Dufuna-CodeCamp/Dufuna-Fem pull request #611
Opened 2021-02-16 20:29 UTC by rubyade

![Screenshot (61)](https://user-images.githubusercontent.com/73884443/108118049-12f32380-709e-11eb-99a8-84f971692f94.png)

2021-02-17 09:15 UTC, adaugochi requested changes
For the last task, the issue I was pointing out wasn't fixed before the PR got `merged`. You make likely fix it along with this PR.

Well done @rubyade

2021-02-17 09:15 UTC, adaugochi commented on submissions/rubyAdeniregun/php/orderpage.php
> +    $sql= "SELECT * FROM order_details";
The query you are to write for this task affects about 3 to 4 tables. That's why you were thought things like relationships on tables using foreign keys and the use of `join` statement

2021-02-17 09:15 UTC, adaugochi commented on submissions/rubyAdeniregun/php/listview.php
> +                echo "<td><button type=button><a href='orderpage.php'>VIEW</a></button>" . $row['actions'] . "</td>";
Also, the idea is to get all the order details of each customer you have on this page. Say for example you have Adaa as a customer, You are supposed to return details about customer Adaa when I click on the `View` button associated with Adaa

2021-03-10 10:28 UTC, Ireti203 commented on submissions/rubyAdeniregun/php/orderpage2.php
> +    //$customer_orders = isset($_COOKIE['data']) ? unserialize($_COOKIE['data']) : $data->list($id);
Remove commented out codes

2021-03-10 10:52 UTC, Ireti203 approved these changes

2021-03-10 10:53 UTC, merged