[DFMD-27] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-Fem pull request #631
Opened 2021-02-19 17:55 UTC by MoyinoluwaA

2021-02-20 19:49 UTC, adaugochi requested changes
Also, write an insert query to insert records inside these tables

2021-02-20 19:49 UTC, adaugochi commented on submissions/moyinoluwaAdenuga/database/init.sql
> +    log_in_date DATETIME NOT NULL,
`created_at` is better

2021-02-20 19:49 UTC, adaugochi commented on submissions/moyinoluwaAdenuga/database/init.sql
> +	product_added_at DATETIME NOT NULL,
same here

2021-02-20 19:49 UTC, adaugochi commented on submissions/moyinoluwaAdenuga/database/init.sql
> +CREATE TABLE registered_addresses (
`registered_customer_addresses` is better

2021-02-20 19:49 UTC, adaugochi commented on submissions/moyinoluwaAdenuga/database/init.sql
> +CREATE TABLE customer_order (
Table name should be pluralized

2021-02-20 19:49 UTC, adaugochi commented on submissions/moyinoluwaAdenuga/database/init.sql
> +CREATE TABLE customer_item (
Table name should be pluralized

2021-02-20 22:06 UTC, MoyinoluwaA commented
@adaugochi I have made the necessary corrections. Thanks

2021-02-22 09:25 UTC, adaugochi approved these changes

2021-02-22 09:26 UTC, merged