[DFMD-37] Database Design For A Transportation Company
Dufuna-CodeCamp/Dufuna-Fem pull request #648
Opened 2021-02-22 09:48 UTC by MoyinoluwaA

2021-02-22 11:39 UTC, Ireti203 requested changes

2021-02-22 11:39 UTC, Ireti203 commented on submissions/moyinoluwaAdenuga/database/transport.sql
> +	age INT NOT NULL,
Kindly use varchar here

2021-02-22 14:04 UTC, MoyinoluwaA commented
@Ireti203 made the change. Thanks

2021-02-23 10:16 UTC, Ireti203 approved these changes

2021-02-23 10:16 UTC, merged