[139] Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #68
Opened 2020-11-18 21:59 UTC by damlois

This PR contains Implementation for my product page task using HTML.

See screenshots below.
![image](https://user-images.githubusercontent.com/8555805/99593165-87f88380-29f1-11eb-8bb3-0896dd3bd791.png)
![image](https://user-images.githubusercontent.com/8555805/99593218-9d6dad80-29f1-11eb-8ae8-fbfef8155cdb.png)

2020-11-19 10:43 UTC, Ireti203 requested changes

2020-11-19 10:43 UTC, Ireti203 commented on submissions/loisAdegbohungbe/HTML/product.html
> +    </footer>
Format the footer tag properly.

2020-11-19 10:43 UTC, Ireti203 commented on submissions/loisAdegbohungbe/HTML/product.html
> +
Remove whitespace.

2020-11-19 10:43 UTC, Ireti203 commented on submissions/loisAdegbohungbe/HTML/product.html
> +
Remove whitespace

2020-11-19 10:43 UTC, Ireti203 commented on submissions/loisAdegbohungbe/HTML/product.html
> +    <nav>
Why are you using a nav tag here? Nav tags are used for major blocks of navigation links. You can use a section tag instead

2020-11-19 10:43 UTC, Ireti203 commented on submissions/loisAdegbohungbe/HTML/product.html
> +
Remove whitespace.

2020-11-19 10:43 UTC, Ireti203 commented on submissions/loisAdegbohungbe/HTML/product.html
> +
Remove whitespace

2020-11-19 21:16 UTC, damlois commented on submissions/loisAdegbohungbe/HTML/product.html
> +    </footer>
How do I do that @Ireti203 .

2020-11-20 09:02 UTC, Ireti203 approved these changes

2020-11-20 09:04 UTC, merged