[DFFS-4] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-Fem pull request #687
Opened 2021-03-03 15:07 UTC by thebadmos

![Screenshot (14)](https://user-images.githubusercontent.com/49362680/109825865-88ccc280-7c3a-11eb-8e8d-5d1a96ba525e.png)

2021-03-04 08:15 UTC, Ireti203 requested changes
Weldone @thebadmos. But you are not doing what the task requested. You are not to create a separate file for navigation. You should add the navigation links to previously existing  pages. E,g if I click on "Products" on the Contact us page, it takes me to the Products page.

2021-03-04 11:37 UTC, adaugochi requested changes
Your `product.html` file should be inside your `html` folder not your `html-forms` folder

2021-03-04 12:35 UTC, Ireti203 requested changes

2021-03-04 12:35 UTC, Ireti203 commented on submissions/OlamijiBadmos/html-forms/contact.html
> +    <h4>The products in the store are  <a href="product.html">Product Page</a> </h4>
Include the link to the contact page too. Also, add the navigation links on the product.html file

2021-03-05 08:47 UTC, adaugochi requested changes

2021-03-05 08:47 UTC, adaugochi commented on submissions/OlamijiBadmos/html/product.html
>       </ol>
Remove newline spaces from line 40-42

2021-03-10 09:01 UTC, adaugochi approved these changes

2021-03-10 09:01 UTC, merged