[DFFE-27] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-Fem pull request #691
Opened 2021-03-03 22:31 UTC by lorlahdey

@Ireti203

2021-03-04 09:20 UTC, lorlahdey commented
@Ireti203

2021-03-04 09:51 UTC, adaugochi requested changes

2021-03-04 09:51 UTC, adaugochi commented on submissions/lawalLolade/database/init.sql
> +);
Insert some data into the products table

2021-03-04 11:19 UTC, lorlahdey commented
@adaugochi

2021-03-04 11:39 UTC, adaugochi requested changes

2021-03-04 11:39 UTC, adaugochi commented on submissions/lawalLolade/database/init.sql
> +	(1, 2, 'Cherry Blossom', 'A feminine arrangement of pale pink Asiatic Lilies alongside hot pink carnations, pink and white two tone spray carnations and white Freesias.', 'C:\Users\Mr L.O. Lawal\Des
use image URL rather than pointing to a path on your local machine

2021-03-05 17:53 UTC, lorlahdey commented
@adaugochi @Ireti203

2021-03-07 11:34 UTC, adaugochi commented
> 
> 
> @adaugochi @Ireti203

use image URL rather than pointing to a path on your local machine

2021-03-07 13:22 UTC, lorlahdey commented
I made the changes already

2021-03-09 09:16 UTC, adaugochi requested changes
Instead of doing this `'C:\Users\Mr L.O. Lawal\Desktop\Dufuna-Fem\submissions\lawalLolade\HTML\images\Prod2.jpeg` use an image url from google

2021-03-09 16:11 UTC, lorlahdey commented
@adaugochi

2021-03-10 09:02 UTC, adaugochi approved these changes

2021-03-10 09:02 UTC, merged