[CSFS-153] Article Publishing Endpoint
Dufuna-CodeCamp/Dufuna-Fem pull request #696
Opened 2021-03-05 09:43 UTC by modupeadeonojobi

![Screenshot (113)](https://user-images.githubusercontent.com/66411673/110096683-77043000-7d9e-11eb-9f4d-3b28a0824d82.png)

2021-03-05 14:18 UTC, adaugochi requested changes
Don't push `.env` just push a sample of the .env file. Don't push `composer.lock` file. Add it to .env

2021-03-05 14:18 UTC, adaugochi commented on submissions/modupeAdeOnojobi/slim/publishing_house/app/controllers/ArticleController.php
> +    #GET ALL ARTICLES
The task didn't ask for this endpoint

2021-03-05 14:18 UTC, adaugochi commented on submissions/modupeAdeOnojobi/slim/publishing_house/app/controllers/ArticleController.php
> +        $articles = Article::where('articles.id', '>', 0)->join('admins', 'articles.created_by', 'admins.id')
Your where condition here is not supposed to be. `id` won't start from `0`

2021-03-05 14:18 UTC, adaugochi commented on submissions/modupeAdeOnojobi/slim/publishing_house/app/models/admin.php
> +
Remove comments when no in use

2021-03-05 14:19 UTC, adaugochi commented
Well done

2021-03-05 15:09 UTC, modupeadeonojobi commented on submissions/modupeAdeOnojobi/slim/publishing_house/app/models/admin.php
> +
Done, kindly review my pull request.

2021-03-07 11:29 UTC, adaugochi requested changes
Also, add composer.lock file in your gitignore. I am still seeing your env file as part of your PR. To make this changes reflect, you have to delete it and do an git add and create the file again. Only push you sample env file

2021-03-08 07:56 UTC, modupeadeonojobi commented
I have done it.

2021-03-08 10:26 UTC, adaugochi requested changes
I am still seeing .env 

![image](https://user-images.githubusercontent.com/43061141/110308953-0b6dcd00-8001-11eb-9ea5-e1f5418a5168.png)
 What I want to see is a sample of your .env file, not  the .env file itself

2021-03-08 10:30 UTC, modupeadeonojobi commented
Can you still see it?

2021-03-09 09:35 UTC, modupeadeonojobi commented
I really don't get what you want me to do.
You said that I should remove .env file and I did just that.
How do I add composer.lock file to a file that I has already be removed?

2021-03-09 15:09 UTC, adaugochi commented
> I really don't get what you want me to do.
> You said that I should remove .env file and I did just that.
> How do I add composer.lock file to a file that I has already be removed?

Sorry, I actually meant that `composer.lock` file should not be part of your PR. Add the `composer.lock` file to `.gitignore`. Same goes with `vendor` and `.env` file. There are not suppose to be part of your PR. They are not meant to be push to the outside

2021-03-10 07:53 UTC, modupeadeonojobi commented
I have done it.

2021-03-10 09:05 UTC, adaugochi approved these changes

2021-03-10 09:06 UTC, merged