[DFFS-27] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-Fem pull request #713
Opened 2021-03-08 13:33 UTC by Mayowa2020

2021-03-08 17:19 UTC, Ireti203 requested changes

2021-03-08 17:19 UTC, Ireti203 commented on submissions/BukkyOyetimehin/database/init.sql
> +);
You created two tables for customers?

2021-03-09 09:12 UTC, adaugochi requested changes

2021-03-09 09:12 UTC, adaugochi commented on submissions/BukkyOyetimehin/database/init.sql
> +    Brand VARCHAR(100),
This column is not part of this table

2021-03-09 09:12 UTC, adaugochi commented on submissions/BukkyOyetimehin/database/init.sql
> +	FOREIGN KEY (admin_login_id) REFERENCES admin_login (id)
The table you are referencing here is different from what you created

2021-03-09 15:06 UTC, adaugochi requested changes

2021-03-09 15:06 UTC, adaugochi commented on submissions/BukkyOyetimehin/database/init.sql
> +    Brand VARCHAR(100),
This column(brand) is not part of this table

2021-03-11 09:03 UTC, adaugochi requested changes

2021-03-11 09:03 UTC, adaugochi commented on submissions/BukkyOyetimehin/database/init.sql
> +ALTER TABLE products CHANGE Brand brand VARCHAR(100);
`brand` should not be a column on the `products` table. Or, is there a place on the task where is it mentioned

2021-03-11 10:08 UTC, Ireti203 approved these changes

2021-03-11 10:08 UTC, merged