[DFFS-4] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-Fem pull request #719
Opened 2021-03-09 09:42 UTC by Seyi01

![Screenshot (9)](https://user-images.githubusercontent.com/64793404/110451070-1d647400-80c4-11eb-8177-051581c22097.png)
![Screenshot (10)](https://user-images.githubusercontent.com/64793404/110451095-25bcaf00-80c4-11eb-9d94-08ea1a60dc55.png)

2021-03-09 11:51 UTC, Ireti203 requested changes
The index.html file should be in the HTML folder.

2021-03-09 12:21 UTC, Seyi01 commented
Done ma. Thank you.
![Screenshot (11)](https://user-images.githubusercontent.com/64793404/110469759-527bc100-80da-11eb-924f-990b58f86bf8.png)

2021-03-09 12:22 UTC, Seyi01 commented
Done ma. thank you
![Screenshot (11)](https://user-images.githubusercontent.com/64793404/110469880-7939f780-80da-11eb-9283-c4bd5a4d326d.png)

2021-03-10 08:37 UTC, adaugochi requested changes

2021-03-10 08:37 UTC, adaugochi commented on submissions/seyifunmiOjo/html-forms/contact.html
> +<!DOCTYPE html>
You already created `contact page` for your previous task, why creating it again?

2021-03-11 10:46 UTC, Seyi01 commented
Hi @Ireti203. I have understood and done the needful. There is only one contact page in the submissions folder and the nav links have been added to both it and the products page. Pls review. Thank you.

2021-03-11 11:23 UTC, Ireti203 approved these changes

2021-03-11 11:23 UTC, merged