[DFFE-3]Develop a Contact form page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #731
Opened 2021-03-11 14:07 UTC by Nutan2305

2021-03-11 15:13 UTC, TundeOladejo requested changes

2021-03-11 15:13 UTC, TundeOladejo commented on submissions/Nutan/index.html
> +</form>
Format this block properly

2021-03-11 15:13 UTC, TundeOladejo commented on submissions/Nutan/index.html
> +<body style="margin-left: 20px;margin-top:20px;margin-right: 20px; background-color: paleturquoise">
You are not expected to use any CSS styling for this task. Kindly go through and make changes in other places too.

2021-03-14 20:31 UTC, adaugochi submitted a review, later dismissed
This task should be inside `html-forms` folder. This `html-forms` folder should be inside your name folder

2021-03-31 12:00 UTC, adaugochi commented on submissions/Nutan/html-forms/index.html
> +<html lang="en">
this file name `index.html` doesn't tell what this file is for. Kindly name it to something like `contact.html`

2021-04-06 09:55 UTC, Ireti203 approved these changes

2021-04-06 09:55 UTC, merged