[CSFS-153] Article Publishing Endpoints
Dufuna-CodeCamp/Dufuna-Fem pull request #753
Opened 2021-03-19 15:18 UTC by rubyade

![Capture49](https://user-images.githubusercontent.com/73884443/111802833-b8ccc480-88ce-11eb-901a-08364e82920a.PNG)

2021-03-21 11:15 UTC, adaugochi requested changes
Well done @rubyade

2021-03-21 11:15 UTC, adaugochi commented on .gitignore
> -# Mac DS_Store Files
You have deleted our `.gitignore` file that is inside the `Dufuna-Fem` folder. Kindly replace what you delete back

2021-03-21 11:15 UTC, adaugochi commented on submissions/rubyAdeniregun/sparkPublishingHouse/.env.sample.txt
> +#Database config
This is not a `.txt` file. Kindly remove the `.txt` extension

2021-03-22 08:37 UTC, adaugochi requested changes
Your code is ok, but your documentation is not. Kindly message me privately let's have a call concerning it.

2021-03-23 14:53 UTC, Ireti203 requested changes

2021-03-23 14:53 UTC, Ireti203 commented on submissions/rubyAdeniregun/sparkPublishingHouse/app/controllers/ArticleController.php
> +        $article->status = 'published';
why are you not getting the status from the db?

2021-03-24 10:27 UTC, Ireti203 approved these changes

2021-03-24 10:27 UTC, merged