[149] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-Fem pull request #76
Opened 2020-11-19 14:20 UTC by OluwaboriShobayo

![image](https://user-images.githubusercontent.com/74042089/99678014-a787be80-2a7a-11eb-900d-98636465ab8c.png)
![image](https://user-images.githubusercontent.com/74042089/99678063-b5d5da80-2a7a-11eb-8a10-d01aca6ea36b.png)

2020-11-19 15:05 UTC, Ireti203 requested changes
I cant see any navigation link on the productPage.

2020-11-19 15:05 UTC, Ireti203 commented on submissions/oluwaboriShobayo/html-forms/contactForm.html
> +        <a href="../ahtml-forms/contactForm.html">Contact Us</a>
is it ahtml-forms or html-forms?

2020-11-19 15:14 UTC, OluwaboriShobayo commented
> I cant see any navigation link on the productPage.

I don't understand what you mean please

2020-11-19 16:24 UTC, Ireti203 commented
> > I cant see any navigation link on the productPage.
> 
> I don't understand what you mean please

You should add navigation links to both pages. I can only see the links on contactForm.html

2020-11-19 16:51 UTC, OluwaboriShobayo commented
> > > I cant see any navigation link on the productPage.
> > 
> > 
> > I don't understand what you mean please
> 
> You should add navigation links to both pages. I can only see the links on contactForm.html

I have checked again; The links are also on productPage.html from line 11 to 15

2020-11-20 08:57 UTC, Ireti203 approved these changes

2020-11-20 08:57 UTC, merged