[139] Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #79
Opened 2020-11-19 17:19 UTC by HalimahOladimeji

![Screenshot 2020-11-19 181420](https://user-images.githubusercontent.com/73618133/99700661-bc248080-2a93-11eb-9919-9465e947da4e.png)
![Screenshot 2020-11-19 181522](https://user-images.githubusercontent.com/73618133/99700667-bdee4400-2a93-11eb-9247-f68dd52fa3c0.png)

2020-11-20 09:13 UTC, Ireti203 requested changes
@HalimahOladimeji This task requires only HTML, I can see some CSS styling in your file. Kindly follow the instructions in the task criteria.

Also, note that when you get to the CSS task, you should have a separate file for your styling. Internal styling is not recommended.

2020-11-20 09:57 UTC, HalimahOladimeji commented
I have made the changes. Kindly review it. Thanks.

On Fri, 20 Nov 2020, 10:13 Ireti203, <notifications@github.com> wrote:

> *@Ireti203* requested changes on this pull request.
>
> @HalimahOladimeji <https://github.com/HalimahOladimeji> This task
> requires only HTML, I can see some CSS styling in your file. Kindly follow
> the instructions in the task criteria.
>
> Also, note that when you get to the CSS task, you should have a separate
> file for your styling. Internal styling is not recommended.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/79#pullrequestreview-535249167>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRVFVNPLAIYGKKOHGZN5CTSQYXMHANCNFSM4T3WAM4Q>
> .
>

2020-11-20 10:02 UTC, Ireti203 requested changes

2020-11-20 10:02 UTC, Ireti203 commented on submissions/HTML/index.html
> +    <div class="column">
The entire file is not properly formatted. Kindly correct this.

2020-11-20 10:03 UTC, Ireti203 commented
Attach an image of your webpage after removing the styling

2020-11-20 10:18 UTC, HalimahOladimeji commented
I have made the changes. I've attached the screenshots here. Thanks

On Fri, 20 Nov 2020, 11:03 Ireti203, <notifications@github.com> wrote:

> Attach an image of your webpage after removing the styling
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/79#issuecomment-731072212>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRVFVL2WHEAFJRFKHTENFDSQY5H5ANCNFSM4T3WAM4Q>
> .
>

2020-11-20 10:30 UTC, Ireti203 requested changes

2020-11-20 10:30 UTC, Ireti203 commented on submissions/HTML/index.html
> +
Remove whitespace

2020-11-20 10:30 UTC, Ireti203 commented on submissions/HTML/index.html
> +
Remove whitespace

2020-11-20 10:30 UTC, Ireti203 commented on submissions/HTML/index.html
> +</div>
The entire file isnt properly formatted. This div is under the body tag, they shouldnt start at the same point. Kindly check the samples in the lesson video/slides.

2020-11-20 10:30 UTC, Ireti203 commented on submissions/HTML/index.html
> +</html>
Kindly format properly. It is good practice to write clean and readable code.

2020-11-20 11:28 UTC, HalimahOladimeji commented
I have made the changes. Find attached.

On Fri, 20 Nov 2020, 11:30 Ireti203, <notifications@github.com> wrote:

> *@Ireti203* requested changes on this pull request.
> ------------------------------
>
> In submissions/HTML/index.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/79#discussion_r527594405>
> :
>
> > @@ -0,0 +1,82 @@
> +<!DOCTYPE html>
> +<html>
> +<head>
> +
>
> Remove whitespace
> ------------------------------
>
> In submissions/HTML/index.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/79#discussion_r527594517>
> :
>
> > @@ -0,0 +1,82 @@
> +<!DOCTYPE html>
> +<html>
> +<head>
> +
> +<body>
> +
>
> Remove whitespace
> ------------------------------
>
> In submissions/HTML/index.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/79#discussion_r527596280>
> :
>
> > +<div class="topnav">
> +  <a class="active" href="#home">Home</a>
> +  <a href="#news">News</a>
> +  <a href="#contact">Contact</a>
> +  <a href="#about">About</a>
> +</div>
>
> The entire file isnt properly formatted. This div is under the body tag,
> they shouldnt start at the same point. Kindly check the samples in the
> lesson video/slides.
> ------------------------------
>
> In submissions/HTML/index.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/79#discussion_r527598094>
> :
>
> > +
> +            <li>Features: Fingerprint (side-mounted), accelerometer, gyro, proximity, compass, barometer,ANT+,Bixby natural language commands and dictation Samsung DeX (desktop experience support)</li>
> +
> +</section>
> +
> +
> +<section>
> +    <p><h3>Description</h3></p>
> +    <p>A mind-blending glass screen that folds like a book.
> +        A hands-free camera that shoots when you wave.
> +        A precision crafted hinge that transforms a cutting-edge smartphone into so much more.
> +        Meet the anything but ordinary Galaxy Z Fold 2 5G.</p>
> +</section>
> +
> +
> +<h4>SIMILAR PRODUCTS YOU MAY BE INTERESTED IN</h4>
> +
> +<ol>
> +  <li>SAMSUNG GALAXY NOTE 9</li>
> +  <li>SAMSUNG GALAXY S20 ULTRA</li>
> +  <li>SAMSUNG GALAXY NOTE 10 LITE</li>
> +  <li>SAMSUNG GALAXY NOTE S20</li>
> +  <li>SAMSUNG GALAXY S10+</li>
> +</ol>
> +<footer>
> +<div class="footer">
> +    <h5>CONTACT US</h5>
> +    <p>Email<br>
> +        <a href="mailto:premiumtechnologies@dufuna.com">premiumtechnologies@dufuna.com</a></p>
> +        <p>
> +            <ul>
> +                <li><a href="https://www.twitter.com">Twitter</a></li>
> +                <li><a href="https://www.linkedin.com">LinkedIn</a></li>
> +                <li><a href="https://www.medium.com">Medium</a></li>
> +            </ul>
> +        </p>
> +        <p &copy; PremiumTechnologies</p>
> +    </div>
> +</footer>
> +</body>
> +</html>
>
> Kindly format properly. It is good practice to write clean and readable
> code.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/79#pullrequestreview-535302671>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRVFVPFUBW43MJ7AKDOCIDSQZAMPANCNFSM4T3WAM4Q>
> .
>

2020-11-23 07:47 UTC, Ireti203 commented
Kindly change the screenshot attached to this PR to what you currently have. The one you uploaded initially has CSS, kindly remove it and update.

2020-11-23 08:16 UTC, HalimahOladimeji commented
I have done that. Kindly check it. Thanks.

On Mon, 23 Nov 2020, 08:47 Ireti203, <notifications@github.com> wrote:

> Kindly change the screenshot attached to this PR to what you currently
> have. The one you uploaded initially has CSS, kindly remove it and update.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/79#issuecomment-731987763>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRVFVLAZLZGMNWV4NPDGNTSRIHSFANCNFSM4T3WAM4Q>
> .
>

2020-11-23 09:09 UTC, Ireti203 approved these changes

2020-11-23 09:09 UTC, merged