[DFMD-4] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-Fem pull request #792
Opened 2021-03-31 12:20 UTC by Mistura-Yusuf

I just add page navigation to my pages. Please review

2021-03-31 13:48 UTC, Ireti203 requested changes

2021-03-31 13:48 UTC, Ireti203 commented on submissions/misturaYusuf/html-forms/contact-form.html
> +		<h1><a href="file:///C:/Users/HP/Desktop/Dufuna-Fem/submissions/misturaYusuf/html/product-page.html">MISSTYB'S GLAMOROUS TOUCH</a></h1>
This file path can only work on your computer. I don't have this exact directory. You can update the link to '../html/product-page.html'

2021-03-31 13:48 UTC, Ireti203 commented on submissions/misturaYusuf/html-forms/contact-form.html
> +			<li><b><a href="file:///C:/Users/HP/Desktop/Dufuna-Fem/submissions/misturaYusuf/html/product-page.html">Product</a></li></b></li>
Same here

2021-03-31 13:48 UTC, Ireti203 commented on submissions/misturaYusuf/html-forms/contact-form.html
> +			<li><b><a href="file:///C:/Users/HP/Desktop/Dufuna-Fem/submissions/misturaYusuf/html/product-page.html">Product</a></li></b></li>
You should also add the link to the contact-form

2021-03-31 13:48 UTC, Ireti203 commented on submissions/misturaYusuf/html/product-page.html
> +		<h1><a href="product-page.html">MISSTYB'S GLAMOROUS TOUCH</a></h1>
Add the link to the contact-form

2021-04-01 12:22 UTC, Ireti203 commented
Ensure it navigates on your computer.

2021-04-01 12:44 UTC, Mistura-Yusuf commented
The links navigates to the respective pages now. Please review. Thank you

2021-04-02 11:35 UTC, Mistura-Yusuf commented
Please review my PR

2021-04-04 08:16 UTC, adaugochi approved these changes

2021-04-05 15:03 UTC, Ireti203 approved these changes

2021-04-05 15:03 UTC, merged