[DFFA-4] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-Fem pull request #811
Opened 2021-04-10 14:37 UTC by Aarinolaa

I am not sure what happened to my files, i could not find them, seems they were deleted. So I created a new request. Thanks

![image](https://user-images.githubusercontent.com/75532208/114273531-4a34df80-9a12-11eb-9599-8a7cdc60dc8b.png)
![image](https://user-images.githubusercontent.com/75532208/114273554-6769ae00-9a12-11eb-99ec-11f55ccd57ad.png)

2021-04-10 17:46 UTC, adaugochi requested changes
You are to create a link between your already existing page. Such that if I am on the product page and I click on `contact us`, it takes me to contact page and vice versa. You are not expected to create a new file

2021-04-10 17:48 UTC, Aarinolaa commented
Hi Ada, like I had explained to Ireti earlier, I couldn’t access the
previous file hence my creating a new. Please advise if you can view the
previous one. Thank you

On Sat, 10 Apr 2021 at 18:46, Maryfaith Mgbede ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> You are to create a link between your already existing page. Such that if
> I am on the product page and I click on contact us, it takes me to
> contact page and vice versa. You are not expected to create a new file
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/811#pullrequestreview-632940240>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASAIPMEJYPOWMG2K4RNE7CDTICFHLANCNFSM42WSHEKQ>
> .
>

2021-04-12 08:32 UTC, adaugochi reviewed
![image](https://user-images.githubusercontent.com/43061141/114364479-5b483280-9b71-11eb-933d-fb6e390cfeae.png)
![image](https://user-images.githubusercontent.com/43061141/114364547-6ac77b80-9b71-11eb-9a60-663735d99911.png)

Both files are already existing. If the file is not visible on your local, it means you haven't pulled from upstream yet to update those changes.

Kindly checkout to `master` and pull from `upstream master`.
Before pulling from upstream, check if you have set `upstream` by running `git remote -v`. If you see 4 links (i.e 2 `origin` and 2 `upstream`) it means you have set `upstream` else run this command `git remote add upstream https://github.com/Dufuna-CodeCamp/Dufuna-Fem` to set `upstream`

2021-04-12 12:47 UTC, Aarinolaa commented
i have updated the file as requested, kindly review. Thanks

2021-04-13 09:17 UTC, adaugochi commented
> i have updated the file as requested, kindly review. Thanks

You still have done what you are told

2021-04-13 09:45 UTC, Aarinolaa commented
Hi Ada, I don’t understand what you mean please.

On Tue, 13 Apr 2021 at 10:18, Maryfaith Mgbede ***@***.***>
wrote:

> i have updated the file as requested, kindly review. Thanks
>
> You still have done what you are told
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/811#issuecomment-818586055>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASAIPMA6TIEBP3LTWSLGMPLTIQD4XANCNFSM42WSHEKQ>
> .
>

2021-04-14 09:27 UTC, Ireti203 requested changes
You don't need to create a navigationpage.html file. What you should do is to add the links to the previously existing files i.e on the product page file, add the link to the contact page and product page, do same on the contact page too. Also, remove the two images in the HTML-FORMS folder, they have no use there.

2021-04-14 10:11 UTC, Aarinolaa commented
Hi Ireti,
Please is there someone I can speak with? Because I am not certain this
mail exchange is working for me. I need to hear someone tell me exactly how
to achieve this as it seems I am not understanding it.
I don’t have the previous files because my pc crashed and i lost my
documents hence my re-doing the work.
I need your help please.
Regards,

On Wed, 14 Apr 2021 at 10:27, Ireti203 ***@***.***> wrote:

> *@Ireti203* requested changes on this pull request.
>
> You don't need to create a navigationpage.html file. What you should do is
> to add the links to the previously existing files i.e on the product page
> file, add the link to the contact page and product page, do same on the
> contact page too. Also, remove the two images in the HTML-FORMS folder,
> they have no use there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/811#pullrequestreview-635406048>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASAIPMBTCGXP3NUAIFBTT23TIVNXTANCNFSM42WSHEKQ>
> .
>

2021-04-22 12:44 UTC, Ireti203 requested changes
I thought you earlier pushed the images. Why are you pushing it again?

2021-04-22 12:44 UTC, Ireti203 commented on submissions/arinolaOsagie/HTML-FORMS/contact-form.html
> +        <a href="productpagehtml.html">Product</a> <a href="contactpage.html">Contact Form</a>
I am very sure these links don't redirect when you click them. You should have contact-form.html and not contactpage.html i.e the name of the file. For the product page also, ensure you are using the exact name of the file. 

The links should be in both the product page and contact-form files

2021-04-22 16:26 UTC, Ireti203 approved these changes

2021-04-22 16:27 UTC, merged