[DFFA-2] Develop a Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #827
Opened 2021-04-14 16:53 UTC by Boluwahduro

2021-04-15 10:29 UTC, adaugochi commented on submissions/boluAkintoye/html/index.html
> +            <img src="images/bag.jpg" alt="Brown bag">
The image used here isn't part of your PR. Is there a reason why?

2021-04-15 10:29 UTC, adaugochi commented on submissions/boluAkintoye/html/index.html
> +            <img src= "images/bag2.jpg">
Same here too

2021-04-15 10:31 UTC, Ireti203 requested changes

2021-04-15 10:31 UTC, Ireti203 commented on submissions/boluAkintoye/html/index.html
> +        </ul>
When you are using a "ul" tag, I expect to see a list in it it. Since you are not using a list, you dont need the ul tag here. You should remove it.

2021-04-27 12:38 UTC, Ireti203 approved these changes

2021-04-27 12:38 UTC, merged