[DFFE-156] Build a To-Do App with REACT
Dufuna-CodeCamp/Dufuna-Fem pull request #841
Opened 2021-04-20 14:26 UTC by lorlahdey

@Ireti203 

Web View
![Capture1](https://user-images.githubusercontent.com/19871450/115412784-8e7f6700-a1ec-11eb-92b9-49c13c922aac.PNG)
Mobile View
![Capture2](https://user-images.githubusercontent.com/19871450/115412789-90492a80-a1ec-11eb-854d-df37e9d57dd5.PNG)

2021-04-21 12:50 UTC, Ireti203 commented
This PR  does not have the expected content.

2021-04-21 13:32 UTC, lorlahdey commented
@Ireti203 I don't know why the PR is not showing the content, it's all in my submission folder under my name

2021-04-21 21:08 UTC, lorlahdey commented
@Ireti203 the PR now contains expected contents

2021-04-22 12:37 UTC, Ireti203 requested changes

2021-04-22 12:37 UTC, Ireti203 commented on submissions/lawalLolade/React/to-do-app/src/App.css
> +  /* padding-bottom: 10px; */
Remove commented out code

2021-04-22 12:37 UTC, Ireti203 commented on submissions/lawalLolade/React/to-do-app/src/components/form.js
> +            // todos:prevState.todos.concat(newItem),
remove commented out code

2021-04-23 13:12 UTC, Ireti203 approved these changes

2021-04-23 13:13 UTC, merged