[138] Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #85
Opened 2020-11-20 19:45 UTC by DeeDeji20

2020-11-20 19:53 UTC, DeeDeji20 commented
![cimlet image](https://user-images.githubusercontent.com/64081620/99843805-f9861e00-2b26-11eb-9291-a88600f97e34.png)
![Cimlet images](https://user-images.githubusercontent.com/64081620/99843830-ff7bff00-2b26-11eb-8a40-cb26fb02caf6.png)

2020-11-23 11:51 UTC, Ireti203 requested changes

2020-11-23 11:51 UTC, Ireti203 commented on submissions/AdeolaOladeji/HTML/index.html
> +
Remove whitespace

2020-11-23 11:51 UTC, Ireti203 commented on submissions/AdeolaOladeji/HTML/index.html
> +</html>
why are you closing the html tag twice?

2020-11-25 09:27 UTC, Ireti203 approved these changes

2020-11-25 09:27 UTC, merged