[DFFA-10] The Software Developer conditionals
Dufuna-CodeCamp/Dufuna-Fem pull request #887
Opened 2021-05-08 00:05 UTC by Seyi01

![Screenshot (56)](https://user-images.githubusercontent.com/64793404/117518876-68eaaf80-af99-11eb-8ec1-eea73efee4c8.png)
![Screenshot (57)](https://user-images.githubusercontent.com/64793404/117518881-6ab47300-af99-11eb-876b-59dfc79b667c.png)

2021-05-09 16:03 UTC, Ireti203 requested changes
It's best you hold on for a previously opened PR to get merged before opening another. Arrays.js ought not to be a part of this PR. You should remove it, same with the index.html file in the arrays folder.

2021-05-09 20:20 UTC, adaugochi commented
Well done @OmolayoO 

I love your work. But, what you didn't share with us is how it look on laptop or desktop view. I can only see `tablet` and `phone` view

2021-05-10 16:36 UTC, Seyi01 commented
Correction taken ma. Thank you @Ireti203

2021-05-11 08:42 UTC, adaugochi approved these changes

2021-05-11 08:43 UTC, merged