[DFFA-11] Sign-Up Form Validation
Dufuna-CodeCamp/Dufuna-Fem pull request #905
Opened 2021-05-24 12:19 UTC by DevOge

2021-05-24 15:28 UTC, Ireti203 requested changes

2021-05-24 15:28 UTC, Ireti203 commented on submissions/OgeEjim/DOM/signupval.js
> +
Remove commented out code

2021-05-24 15:28 UTC, Ireti203 commented on submissions/OgeEjim/DOM/signupval.js
> +function valFl(firstName,event) {
Kindly rename this function

2021-05-24 15:28 UTC, Ireti203 commented on submissions/OgeEjim/DOM/signupval.js
> +function valNum(number,event) {
same here

2021-05-24 16:12 UTC, DevOge commented on submissions/OgeEjim/DOM/signupval.js
> +function valNum(number,event) {
All done ma

2021-05-25 09:04 UTC, Ireti203 approved these changes

2021-05-25 09:04 UTC, merged