[DFFA-156] Build a To-Do App with REACT
Dufuna-CodeCamp/Dufuna-Fem pull request #924
Opened 2021-06-21 21:58 UTC by DevOge

2021-06-22 11:20 UTC, Ireti203 commented
Attach screenshots of your work

2021-06-22 12:19 UTC, DevOge commented
![reactlook](https://user-images.githubusercontent.com/73588652/122923286-777c0300-d35c-11eb-8013-426b01f36fce.JPG)

2021-06-23 16:24 UTC, ToluAkin requested changes
Well done @DevOge

2021-06-23 16:24 UTC, ToluAkin commented on submissions/OgeEjim/React/todo-list/src/component/overall.js
> +                            this.state?.list?.map((todo, index) => <Card onButtonClick={this.handleDone} index={index} todo={todo} key={index} />)
What are you trying to do here `this.state?.list?` ? @DevOge

2021-06-25 15:10 UTC, DevOge commented
Okay, good evening
.. I haven't quite wrapped my head around react or js yet tho.. I did this
by following tutorials and meeting people, the ? is supposed to help with
errors. I can take it out ... just found out it's not necessary.


On Wed, 23 Jun 2021 at 17:24, ToluAkin ***@***.***> wrote:

> *@ToluAkin* requested changes on this pull request.
>
> Well done @DevOge <https://github.com/DevOge>
> ------------------------------
>
> In submissions/OgeEjim/React/todo-list/src/component/overall.js
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/924#discussion_r657270270>
> :
>
> > +                </div>
> +                <div className="inputContainer">
> +                    <input
> +                        className="form-control"
> +                        name="name"
> +                        type="text"
> +                        onChange={this.handleChange}
> +                        placeholder="create a new todo..."
> +                    />
> +
> +                    <button className="btn btn-primary" onClick={(e) => this.handleCreate(e)} disabled={this.state.inactive} >+</button>
> +                </div>
> +                <div className="mt-4 listContainer">
> +                    <div className="mt-4">
> +                        {
> +                            this.state?.list?.map((todo, index) => <Card onButtonClick={this.handleDone} index={index} todo={todo} key={index} />)
>
> What are you trying to do here this.state?.list? ? @DevOge
> <https://github.com/DevOge>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/924#pullrequestreview-690888772>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRN7LGLPEP7JFXQZZY76BLTUIDFFANCNFSM47COGESQ>
> .
>

2021-07-05 12:15 UTC, closed without merging