[DFFE-156] Build a To-Do App with REACT
Dufuna-CodeCamp/Dufuna-Fem pull request #925
Opened 2021-06-22 20:36 UTC by OluwaboriShobayo

![image](https://user-images.githubusercontent.com/74042089/122995623-bd0eef00-d3a1-11eb-8e8d-c288db384487.png)
![image](https://user-images.githubusercontent.com/74042089/122995668-cbf5a180-d3a1-11eb-9438-41b25344e4d4.png)

2021-06-23 16:20 UTC, ToluAkin requested changes
@OluwaboriShobayo Well done. You added the content of package-lock.json in your .gitignore, kindly remove it.

2021-06-23 16:20 UTC, ToluAkin commented on submissions/oluwaboriShobayo/React/to-do-app/src/Components/Footer.js
> +            <span className="item1">{todos.filter(todo => todo.completed === false).length} Items left</span>
I think you should use a more descriptive class name like items-left, all-items, active-items etc @OluwaboriShobayo

2021-06-23 16:20 UTC, ToluAkin commented on submissions/oluwaboriShobayo/React/to-do-app/src/Components/Form.js
> +        console.log(e.target.value);
Remove this console.log

2021-06-23 16:20 UTC, ToluAkin commented on submissions/oluwaboriShobayo/React/to-do-app/src/Components/Form.js
> +const Form = ({setInputText, todos, setTodos,  inputText }) => {
You can set state here instead of passing it as props

2021-06-23 16:20 UTC, ToluAkin commented on submissions/oluwaboriShobayo/React/to-do-app/src/Components/Form.js
> +                ...todos, {text:inputText, completed:false, id:Math.random()}
I think you should extend this Math.random to like 10,000 so that the likelihood of having a duplicate index is slim

2021-06-23 16:20 UTC, ToluAkin commented on submissions/oluwaboriShobayo/React/to-do-app/src/index.js
> +  <React.StrictMode>
Remove strictmode here

2021-06-23 16:20 UTC, ToluAkin commented on submissions/oluwaboriShobayo/React/to-do-app/src/Components/Todo.js
> +
You can set state here instead of passing it as props.

2021-06-25 14:03 UTC, ToluAkin requested changes
![image](https://user-images.githubusercontent.com/38213766/123436144-3edf6200-d5c6-11eb-881e-f840b6054473.png)
![image](https://user-images.githubusercontent.com/38213766/123436416-8534c100-d5c6-11eb-9140-add95bbb0d02.png)

This is not responsive @OluwaboriShobayo

2021-06-29 16:04 UTC, Ireti203 commented
Kindly update the screenshots attached to your PR showing the changes you made

2021-06-29 17:29 UTC, OluwaboriShobayo commented
![image](https://user-images.githubusercontent.com/74042089/123840380-280e7780-d906-11eb-876e-2f72a81e0ff8.png)
![image](https://user-images.githubusercontent.com/74042089/123840429-378dc080-d906-11eb-9ad8-5b73fbe649fc.png)
![image](https://user-images.githubusercontent.com/74042089/123841253-3ad57c00-d907-11eb-9317-ea8d9b21fe6d.png)

2021-06-30 14:14 UTC, ToluAkin requested changes
Well done on the update done. I noticed that I could submit an empty input field, can you make sure that does not happen.
Still on responsiveness, check this out @OluwaboriShobayo 
![image](https://user-images.githubusercontent.com/38213766/123976183-dae9de80-d9b5-11eb-8a0f-91d410b8858d.png)

2021-07-09 11:43 UTC, Ireti203 approved these changes

2021-07-09 11:43 UTC, merged