[138] Product Page using HTML -Frontend
Dufuna-CodeCamp/Dufuna-Fem pull request #93
Opened 2020-11-22 08:53 UTC by Immaculeta1

built the html product page

2020-11-22 09:09 UTC, Immaculeta1 commented
![screen1](https://user-images.githubusercontent.com/74491329/99899553-9624f900-2caa-11eb-96b2-c97646eda88c.PNG)
![screen2](https://user-images.githubusercontent.com/74491329/99899555-9d4c0700-2caa-11eb-9ef0-eeb7ad4a6228.PNG)
![screen3](https://user-images.githubusercontent.com/74491329/99899564-a9d05f80-2caa-11eb-9f69-4cd62a7b0e95.PNG)
![screen4](https://user-images.githubusercontent.com/74491329/99899565-aa68f600-2caa-11eb-88d7-4fe678ca7e2b.PNG)

2020-11-23 07:51 UTC, Ireti203 requested changes

2020-11-23 07:51 UTC, Ireti203 commented on submissions/nwokejeme-immaculeta/html/product.html
> +                    </diV>
Kindly correct this. It is div not diV

2020-11-23 07:53 UTC, Ireti203 requested changes
Why are you using classes already when you havent started styling?

2020-11-23 08:46 UTC, adaugochi approved these changes

2020-11-23 08:47 UTC, merged