[137] Product Page using HTML
Dufuna-CodeCamp/Dufuna-Fem pull request #94
Opened 2020-11-22 15:46 UTC by RafiatAmin

![Screen Shot 2020-11-21 at 6 20 27 PM](https://user-images.githubusercontent.com/46797474/99908314-c5316f80-2c96-11eb-84c8-7334edbffbe1.png)
![Screen Shot 2020-11-21 at 6 20 45 PM](https://user-images.githubusercontent.com/46797474/99908323-cc587d80-2c96-11eb-89c9-2ac971d4f10c.png)

2020-11-23 08:53 UTC, Ireti203 requested changes

2020-11-23 08:53 UTC, Ireti203 commented on submissions/rafiatAminu/HTML/productPage.html
> +        </ul>
Format here properly

2020-11-23 08:53 UTC, Ireti203 commented on submissions/rafiatAminu/HTML/productPage.html
> +    <p> &copy; 2020 Raf Phone Stores</p>
Format properly

2020-11-23 10:18 UTC, RafiatAmin commented on submissions/rafiatAminu/HTML/productPage.html
> +        </ul>
I have. Kindly review. Thanks.

2020-11-24 09:12 UTC, Ireti203 approved these changes

2020-11-24 09:12 UTC, merged